### ISSUE TITLE
It's Bayes all the way up missing images

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#1011]
From intercom:

In the article "It's Bayes all the way up", a picture is missing with a broken link next to it after "Organic psychosis like schizophrenia might involve..."

**Comment by Raemon** [comment]
This particular image looks like it's probably gone forever.

Updating on the "man, we should make images get copied over to LW in a seamless way so this doesn't keep happening."

**Comment by jimrandomh** [comment]
The post is https://www.lesswrong.com/posts/KrEwDMN4YXp5YWD45/it-s-bayes-all-the-way-up . Looks like archive.org has the image. https://web.archive.org/web/20140530040630/http://blog.brainfacts.org/wp-content/uploads/albert6.jpg .

**Comment by jimrandomh** [comment]
All images from that post are now on Cloudinary.
