### ISSUE TITLE
Replicated sequences in library

### ISSUE THREAD

**Issue by pranomostro** [LessWrong2/Lesswrong2#1016]
Maybe I'm overly pedantic here, but "Overly Convenient Excuses" and "Argument and Analysis" are both in their respective sequences collection and on the library page.
It would feel more "right" to me to remove those from https://www.lesswrong.com/library and keep them in https://www.lesswrong.com/rationality and https://www.lesswrong.com/codex.

**Comment by Raemon** [comment]
Right now we use the library page to determine which things show up on the
"Recommended Sequences" on the frontpage (where the top three things in the
library show up there)

This isn't great and we should probably update to a separate list for the
reason you mention.

**Comment by pranomostro** [comment]
Reason: Now the Embedded Agency sequence is first, and this issue feels a lot like clutter.
