### ISSUE TITLE
Posts that can't be found via search, but are still accessible

### ISSUE THREAD

**Issue by pranomostro** [LessWrong2/Lesswrong2#1017]
Apparently, some older posts can't be found with the search function, but are still accessible with their old links. Examples from the old fun theory sequence:

* [High Challenge](https://www.lesswrong.com/posts/29vqqmGNxNRGzffEj/high-challenge)
* [Amputation of Destiny](https://www.lesswrong.com/posts/vwnSPgwtmLjvTK2Wa/amputation-of-destiny)
* [Serious Stories](https://www.lesswrong.com/posts/6qS9q5zHafFXsB6hf/serious-stories)
* [Higher Purpose](https://www.lesswrong.com/posts/5Pjq3mxuiXu2Ys3gM/higher-purpose)

Searching them results only in tangentially related links, but not the real posts.

**Comment by pranomostro** [comment]
Update:

Some of the above can no be found, but there's still some missing:

* [The Born Probabilities](https://www.lesswrong.com/posts/3ZKvf9u2XEWddGZmS/the-born-probabilities)
* [Amputation of Destiny](https://www.lesswrong.com/posts/vwnSPgwtmLjvTK2Wa/amputation-of-destiny)
* [Higher Purpose](https://www.lesswrong.com/posts/5Pjq3mxuiXu2Ys3gM/higher-purpose)

**Comment by jimrandomh** [comment]
This was a problem with the Algolia index, which gets updated incrementally, but only gets fully rebuilt with a manual process. We (finally) did an index rebuild as part of the AIAF import, and that seems to have fixed these old posts.
