### ISSUE TITLE
loading state every 20s shifts page contents

### ISSUE THREAD

**Issue by Zolmeister** [LessWrong2/Lesswrong2#1069]
the [`RecommendedReadingWrapper`](https://github.com/LessWrong2/Lesswrong2/blob/c18040aa9aed4c0024f6c0afd8b033213dacd8e3/packages/lesswrong/components/sequences/RecommendedReadingWrapper.jsx#L6) component (referenced [here](https://github.com/LessWrong2/Lesswrong2/blob/df4da84613b2f6e5d3439e51a6ca2292d916740d/packages/lesswrong/components/posts/PostsPage.jsx#L402)) has `loading` set to `true` every 20s because of a graphql network query.

The div height changes, and makes reading articles/comments infuriating.
I could not find the interval/polling mechanism in the source

**Comment by Discordius** [comment]
Ah, sorry. This is a bug introduced in a recent upgrade. Should be fixed in the PR above.
