### ISSUE TITLE
The LW2 API is not documented

### ISSUE THREAD

**Issue by andrew-vant** [LessWrong2/Lesswrong2#1085]
I asked after API documentation a few months ago in a comment thread, but never filed an issue about its absence. Figured I'd correct that.

(Context: I'd like to write a local client for LW2. A stable API clearly exists, because Greater Wrong uses it, but as far as I can tell there are no docs.)

**Comment by jimrandomh** [comment]
There is auto-generated documentation and a query interface you can play with at https://www.lesswrong.com/graphiql . "Stable API" is a bit of an exaggeration; most of the API machinery comes from `VulcanJS`, which we've built upon. We don't promise that things won't change significantly, and they have changed significantly within the last month (when we upgraded to Vulcan 1.12).
