### ISSUE TITLE
Consider using CKEditor framework

### ISSUE THREAD

**Issue by jglamine** [LessWrong2/Lesswrong2#1096]
I ran across this WYSIWIG editor framework today. At a cursory glance it seems very well made. It's open source but seems well supported since it's the main product of CKSource. It looks like the company has been around for a while so it's unlikely to be abandoned anytime soon.

It might be worth looking into to see if their plugin framework has enough flexibility for the features you're planning.

It has support for realtime-collaborative editing built-in, which could be a major plus if you ever plan on adding those kinds of features to LessWrong.

https://ckeditor.com/ckeditor-5/

**Comment by Discordius** [comment]
I looked into it, and really didn't like the plugin architecture, and it seemed also really hard to combine with React. But it's been a while, and I don't trust past-me's judgement super much on this, so might be worth reevaluating.

**Comment by jglamine** [comment]
Cool, good it know it's already on your radar

**Comment by jimrandomh** [comment]
This is currently shipped for users opted-in to beta features, but not yet default..
