### ISSUE TITLE
Fix scrolling on the search results

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#1277]

**Comment by jimrandomh** [comment]
When you scroll down with the search results open, weird things happen. Which exact weird things depend on the precise timing of the scroll--in particular whether you scroll more than a topbar-height in the time it takes for the topbar to do a hide animation. Additional bad things happen if the window-height is shorter than the height of the results box (as it will be on mobile), or narrower than the width of the results box (again, mobile).
