### ISSUE TITLE
Purged users still in unreviewed posts

### ISSUE THREAD

**Issue by vaniver** [LessWrong2/Lesswrong2#1430]
I still see this post ( https://www.lesswrong.com/posts/Zi95veMkmjZ25sFop/on-lot-to-not-cited-man ) by nowflake in the admin sidebar as an unreviewed post, but when I go to edit their page to purge them I see they've already been purged. [It might also be nice that, when deleted things render for admins, it's obvious that they're deleted for other users, instead of requiring an incognito window to check.]

**Comment by Discordius** [comment]
If you refresh this goes away. Making this update right after purging would be nice, but is actually a bit of a pain.
