### ISSUE TITLE
Moderation Guidelines look janky when Frontpage comment guidelines are present

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#1462]
The moderation guidelines on frontpage posts currently look like this:

![screen shot 2019-01-02 at 16 48 29](https://user-images.githubusercontent.com/101191/50619481-49fe1f00-0eae-11e9-8b96-dbf062c31e91.png)

This is bad because the "Frontpage commenting guidelines" heading line is in a font which incorrectly communicates its relation to the rest of the text; it looks like it's part of the user's moderation guidelines, rather like than a heading.

Also, the "Easy Going - I just delete obvious spam and trolling." line looks like a link, but isn't.

**Comment by Discordius** [comment]
Fixed this in a PR yesterday
