### ISSUE TITLE
Show more of title on mobile

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#1517]
On mobile, due to a combination of screen width, lack of line wrapping, font size, and not squeezing out every possible pixel, you only see the first ~three words of post titles in `PostsItem`. This is quite annoying.

**Comment by Raemon** [comment]
I have a fix in the work for this but depends a bit on consensus on where the frontpage refactor is going.

**Comment by jimrandomh** [comment]
Fixed awhile ago by the PostsItem redesign.
