### ISSUE TITLE
Feature Request: Co-authored posts show up on all authors' profiles

### ISSUE THREAD

**Issue by aarongertler** [LessWrong2/Lesswrong2#1569]
Right now, co-authoring a post links an user's name to the post, but that post won't show up on their profile. This makes it harder to see all of the posts to which a user has contributed,

**Comment by jimrandomh** [comment]
This is handled for the specific case where you're sorting by New, but not for the other sort orders (eg Top, recentCOmments). Issue #1746 for the remaining cases.
