### ISSUE TITLE
Allow time-zone specific date resolving for events

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#1577]
Email from Scott: 

(writing you about this because I can't remember if anyone else would be better; if someone is let me know and they'll get this next time).

A reader complained that the meetups sidebar on my site says there is an SF meetup on December 18th, but the meetup is really on December 17.

I checked and this appears to be true. The LW post it's going to correctly says it is on the 17th ( https://www.lesswrong.com/events/qfLpZvpfMAHLwymcE/san-francisco-meetup-deep-questions ), so I'm not sure what's going wrong.

Please pass this on to anyone who might be able to help.

Thanks,
Scott

From Taymon: 

Sorry this got lost in my inbox. IIRC I brought up a related issue in https://www.lesswrong.com/posts/E5DLTR9PP7axkffSM/using-the-lesswrong-api-to-query-for-events#83gQx9SuNreidwdxA.

Hitting the Google Maps API from SSC would complicate the plugin (which really wants to be kept simple so it doesn't break) enough that I'd rather just leave the bug unfixed. On the other hand, if LW implemented the changes required to make available the local civil time of each event, I could use that.

**Comment by jimrandomh** [comment]
The problem is that the date displayed on the sidebar is given in GMT, rather than in the user's local timezone (which is what they see on Less Wrong), or the time zone of the event location (which would be ideal).

**Comment by jimrandomh** [comment]
Resolved awhile ago, with the addition of endpoints that use the meetup location and the Google Maps API to determine the time zone.
