### ISSUE TITLE
User page route is too brittle

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#1619]
Sometimes you want to go to a user page by typing `lesswrong.com/users/<username>` into the address bar. This can theoretically sometimes work, but in practice, it usually doesn't, because:
 * It's case-sensitive but must be all-lowercase
 * There can be mismatches between username and display name, and the username is what's used
 * The `/users/` part of the route doesn't match old-LessWrong or reddit and doesn't accept alternatives, like `/u/` or `/user/`
All of these are pretty easy to fix, except perhaps the username-vs-displayname issue (which may run into duplication issues).

**Comment by Raemon** [comment]
test foo
