### ISSUE TITLE
Truncated comments that begin with quotes should not begin with quotes

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#1745]
It's confusing and/or not a good use of space.

**Comment by jimrandomh** [comment]
Disagree. The interaction between top-quoting and truncation is a bit unfortunate, but causing people to start reading a comment in the middle is very bad and we shouldn't do it.

**Comment by Discordius** [comment]
This seems covered by the new one-line comments omitting them, but the truncated ones not omitting them. Seems like the correct balance to me.
