### ISSUE TITLE
Not returning 404 result code for page not found

### ISSUE THREAD

**Issue by FerociousTruth** [LessWrong2/Lesswrong2#177]
If you go to a url that doesn't exist, either because the post has been deleted or there is no such url, you will see a message that "Sorry, we couldn't find what you were looking for."  However, the HTTP result code is 200.  It should be 404 to indicate that the URL doesn't point to anything.  This can be important for search engine indexing and other automated tools like broken link detectors.

Two example URLs:
- https://www.lesserwrong.com/sdfjgdfkjgndfkgdf
- https://www.lesserwrong.com/posts/QKbzD7zrbCyQEWQya/draft-link/

**Comment by Discordius** [comment]
Indeed. This is a bit more of a Vulcan issue, but we can probably hotfix it if it doesn't get fixed there. But lower priority for now.
