### ISSUE TITLE
PostsPage date hover should show curation date

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#1937]
In PostsItem2, when you hover over the date on a curated post, it shows both the date it was posted and the date it was curated. On PostsPage, the date at the top should do the same thing.

┆Issue is synchronized with this [Trello card](https://trello.com/c/kKqw63VO) by [Unito](https://www.unito.io/learn-more)

**Comment by JanTrooper2** [comment]
This is already solved and should be closed. Who should I ping? @jimrandomh @Discordius ?

**Comment by JanTrooper2** [comment]
As far as I can see this issue seems to solved. If not I would like to know how to reproduce it.

**Comment by Discordius** [comment]
Yep, resolved
