### ISSUE TITLE
Timestamps on comments should show detailed time on hover

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#194]

**Comment by Raemon** [comment]
I think an issue with this is that we don't have a good hover-over-tooltip component that doesn't require an Icon. It wouldn't be too hard to create one, except we have vague plans to migrate to Material UI v1, which I believe comes with a more reasonable hover-over-tooltip.

But, don't know when we'll actually get around to that.

**Comment by jimrandomh** [comment]
This was done in the timezone-handling PR.
