### ISSUE TITLE
Password reset is an oracle as currently implemented

### ISSUE THREAD

**Issue by synkarius** [LessWrong2/Lesswrong2#1985]
This is a security issue. Malicious users can use the password reset functionality to find emails of LessWrong users. 

When entering an email for a reset, if the email does not exist in the database, the site responds with "User not found". 

I suggest two mitigations.

1. Add a delay on responding to both existing and non-existing email addresses. This will not fully prevent timing attacks, but it will at least slow down scripted mass email guessing. Even a 1-second delay would be sufficient.
2. Do not respond with "User not found" for non-existing emails. Respond with "If the email entered exists, then a password recovery email has been sent" for BOTH existing and non-existing emails.

**Comment by Discordius** [comment]
We already have a rate-limiter on that password-reset form. If you press the button a few times, you will see the following error message: 

<img width="243" alt="Screen Shot 2019-05-30 at 11 31 46 AM" src="https://user-images.githubusercontent.com/9090789/58655257-93706000-82ce-11e9-930b-32a6b8c2f2eb.png">

**Comment by Discordius** [comment]
That rate-limit is indeed implemented in Meteor, so I am not very worried about this. 

Will close this for now, but feel free to reopen if you are still concerned.
