### ISSUE TITLE
No author in RSS feed posts

### ISSUE THREAD

**Issue by brendanlong** [LessWrong2/Lesswrong2#210]
See here: https://www.lesserwrong.com/feed.xml

`<item>` should have an `<author>`, which should presumably be people's user names: https://validator.w3.org/feed/docs/rss2.html#ltauthorgtSubelementOfLtitemgt

I think this is a bug in Vulcan but I don't have time to test it right now.

 - In `packages/vulcan-users/lib/fragments.js`, we see that users have a `username` and `displayName`
 - In `packages/example-forum/lib/modules/posts/fragments.js`, we see that posts have a `user` (not `author`)
 - In `packages/example-forum/lib/server/rss.js`, we create an RSS feed item using `post.author`.

Presumably this:

```
    const feedItem = {
      title: post.title,
      description: `${post.htmlBody || ""}<br/><br/>${postLink}`,
      author: post.author,
      date: post.postedAt,
      guid: post._id,
      url: (getSetting('RSSLinksPointTo', 'link') === 'link') ? Posts.getLink(post) : Posts.getPageUrl(post, true)
    };
```

Should be this:

```
    const feedItem = {
      title: post.title,
      description: `${post.htmlBody || ""}<br/><br/>${postLink}`,
      author: post.user.displayName || post.user.userName,
      date: post.postedAt,
      guid: post._id,
      url: (getSetting('RSSLinksPointTo', 'link') === 'link') ? Posts.getLink(post) : Posts.getPageUrl(post, true)
    };
```

**Comment by brendanlong** [comment]
Why this matters: LessWrong 2.0 is an aggregator, but in RSS feeds you can tell who wrote any individual article.

![screenshot from 2017-10-12 11-27-39](https://user-images.githubusercontent.com/1447206/31504432-65121d56-af40-11e7-8edd-f5572bf97b6f.png)

**Comment by brendanlong** [comment]
Ahh nevermind, `<dc:creator>` should work, but it looks like a bug in my RSS reader, not your feeds.

**Comment by brendanlong** [comment]
Uhh wait.. for some reason I only get an author for `lifelonglearner`. I suspect for some reason they have a `displayName` set and no one else does. We should fall back to username if they don't?

**Comment by brendanlong** [comment]
Ohhhh, so the logic is probably reasonable, since `Users.getDisplayName` already has a fallback to user name:

```
Users.getDisplayName = function (user) {
  if (typeof user === "undefined") {
    return "";
  } else {
    return (user.displayName) ? user.displayName : Users.getUserName(user);
  }
};
```

I bet what I'm seeing is that imported feeds (from other RSS feeds) don't have a user?

**Comment by Discordius** [comment]
Hmm, interesting. I haven't spend much time debugging the RSS, so I will debug this when we get around to it.

**Comment by jimrandomh** [comment]
Based on http://www.lowter.com/blogs/2008/2/9/rss-dccreator-author it appears that the right thing to do is fill in `dc:creator` and ignore `author` which, for some reason, is required to be an email address.

**Comment by jimrandomh** [comment]
And just to keep us on our toes, we're passing an "author" attribute to a library that takes that value and puts it in the `dc:creator` field. But it looks like everything's good here.
