### ISSUE TITLE
Remove URL from the user's profile and replace bio with ory-editor content field

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#225]
The URL field strikes me as fairly useless, and I don't think it make super much sense for us to keep it. But I am hesitant to just remove it since we don't yet have rich-text capabilities in the bio field (i.e. it's currently just plaintext). So before I remove it, I would want to make sure we switch over towards the full editor on people's bio's.

**Comment by malob** [comment]
I tried to update my bio and got the “Schema validation error”. Presumably this is due to me also having an email in the website field?

**Comment by brendanlong** [comment]
I was just coming to GitHub to report the `Schema validation error` and @malob's comment made me try removing my website, which fixed it.
![screenshot from 2017-10-31 18-00-54](https://user-images.githubusercontent.com/1447206/32251055-aef4e032-be65-11e7-8757-9a46c7c1f136.png)

**Comment by matthewfallshaw** [comment]
If you remove the schema (http:// or https://) the website field will allow you to save a website.
(That is, "www.brendanlong.com" will be accepted, "https://www.brendanlong.com/" will provoke the Schema validation error.

**Comment by malob** [comment]
Just noticed though that now when I click the url on my profile page it doesn't work.
