### ISSUE TITLE
Typography and comment-styling rework

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#227]
There are a variety of issues with the current font, and also the readability of the comment section isn't amazing. So I think we should switch our dominant font away from ETBook towards something else, and then also revamp the comment section to have clearer distinctions between comments and generally better information hierarchy.

**Comment by Discordius** [comment]
I think we should do this in three stages: 

1. Change the primary font towards something more readable
2. Revamp the comment section to have better structure
3. Add a setting on post creation that allows you to change between a serif and sans-serif font

**Comment by malob** [comment]
>3. Add a setting on post creation that allows you to change between a serif and sans-serif font.

Does this mean that the author can select if their post will display for everyone with that font. I assume this is motivated by some people preferring the look of sans-serif fonts. If that's the case, a better solution might be to have a user setting for this, and display all body text according to the user's preference. That way the site will have a consistent look.

**Comment by Discordius** [comment]
So, the vision for this is more to tie in the font-choice with the purpose of a post. 

I have to experiment a bit with this. But one implementation that I've been thinking about is to have a toggle button that switches between "Longform Essay" and "Reference Post", and which changes the styling appropriately. 

I don't think the problem is that some people like serif fonts and others don't. The problem is that for highly structured content, such as the LessWrong boring advice repository (and other repositories), or a lot of Luke's posts, the current font-choice doesn't work super well. The current font works really well for longform essay with content that's supposed to be read in long continuous sittings and without skimming, which is a lot of the content on the site, but it's by far from all. 

The idea is to provide an actual abstraction on the page that ties in the font-choice with the content of the page. We'll see how well it will work, but I would much prefer a solution like that, over just having people chose their own font for all posts, since it gets rid of a whole dimension on which one can communicate design abstractions.
