### ISSUE TITLE
"Anonymous" poster is sometimes not anonymous

### ISSUE THREAD

**Issue by moyamo** [LessWrong2/Lesswrong2#2299]
I found some weird behaviour in the comments of the [Ugh Fields](https://www.lesswrong.com/posts/EFQ3F6kmt4WHXRqik/ugh-fields) post.

Initially when the comments are minimized it shows the posters name (Roku).
![Minimized Comments](https://user-images.githubusercontent.com/5392783/63039756-44e16380-bec4-11e9-8243-80aa91293af9.jpg)

But if you click to expand it the posters name becomes [anonymous]
![Expanded Comments](https://user-images.githubusercontent.com/5392783/63039830-73f7d500-bec4-11e9-9a13-92333861c0f4.jpg)

If you minimize again, the poster name remains [anonymous]
![Minimize again](https://user-images.githubusercontent.com/5392783/63039901-97228480-bec4-11e9-8164-c7533bf1ddbc.jpg)

**Comment by Discordius** [comment]
Oh, indeed. I will fix this. Thanks for reporting!

**Comment by Discordius** [comment]
Fixed in: #2300

**Comment by jpaddison3** [comment]
Motion to close.

**Comment by moyamo** [comment]
Not sure what your policies are w.r.t. closing issues. The problem's fixed as far as I can tell. So I'm going to close it. If this is wrong, feel free to reopen.
