### ISSUE TITLE
Invalid post URLs return 200 instead of 404

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#2355]
Caused by this bug in apollo-client: https://github.com/apollographql/apollo-client/issues/3897 . If a graphql query returns an error, then during SSR, graphql returns a loading state rather than an error state. In `PostsPageWrapper`, this means that the SSR winds up returning `200 OK` when it should be returning `404 Not Found`.

This only affects 404s that depend on a database operation; if a URL doesn't match any routes, it will return a 404 correctly.

**Comment by jpaddison3** [comment]
I believe this is done. Motion to close.
