### ISSUE TITLE
AllPosts is showing me the same posts for every year

### ISSUE THREAD

**Issue by ben-pace** [LessWrong2/Lesswrong2#2366]
Last time I was in AllPosts, I set it to show me top posts yearly. I’ve just come back, and now every year is showing me the top posts of all time i.e. the same list each time

<img width="858" alt="Screenshot 2019-08-28 at 20 56 49" src="https://user-images.githubusercontent.com/24915924/63909138-797e1080-c9d6-11e9-9624-6cdca7d7ac64.png">

**Comment by jimrandomh** [comment]
My bad. Fixed in https://github.com/LessWrong2/Lesswrong2/pull/2367 .
