### ISSUE TITLE
When I ctrl-z after adding a link to text, the entire paragraph is replaced with the phrase 'Admin Options'.

### ISSUE THREAD

**Issue by ben-pace** [LessWrong2/Lesswrong2#2403]

**Comment by Discordius** [comment]
I... am both skeptical and confused

**Comment by jimrandomh** [comment]
Which editor? And, is "admin options" an exact string, including capitalization?

**Comment by jimrandomh** [comment]
I can't replicate this.

**Comment by jimrandomh** [comment]
Our current theory is that this was caused by a misbehaving Chrome extension.
