### ISSUE TITLE
Triple-clicking doesn't highlight whole paragraphs if there's an internal link

### ISSUE THREAD

**Issue by ben-pace** [LessWrong2/Lesswrong2#2404]
<img width="699" alt="Screenshot 2019-09-06 at 03 36 50" src="https://user-images.githubusercontent.com/24915924/64421933-a4f89f00-d057-11e9-93c3-bcbaf78d6aec.png">

**Comment by jimrandomh** [comment]
More of a feature request than a bug. There isn't any specification for what triple-click is supposed to do; here's the W3C [talking about whether to standardize it](https://github.com/w3c/selection-api/issues/70). I made a quick attempt to find documentation for how the bounds are determined, and neither Chrome or Firefox have this documented anywhere I could see.

The current behavior is that the selection is a paragraph, except it splits on the LW superscript tag, on LaTeX. The thing that triggers it appears to be the `position: absolute` on the tag, which we want to avoid using for other reasons (it makes it impossible to keep the positioning consistent at different text sizes).

**Comment by jpaddison3** [comment]
Fixed, motion to close
