### ISSUE TITLE
Cannot uncheck 'show low karma posts' on profile page

### ISSUE THREAD

**Issue by ben-pace** [LessWrong2/Lesswrong2#2474]
On profile page, it says "Ben Pace's Posts" and has a gear to the right showing settings for ordering the posts shown. I tried to deselect the 'show low karma' button, but cannot.

**Comment by ForrestWeiswolf** [comment]
I've seen this happen as well, and am going to take a try at fixing it.

**Comment by Discordius** [comment]
@ForrestWeiswolf Thank you so much for fixing this!

**Comment by ForrestWeiswolf** [comment]
Glad I could help! Mark it as closed when you get a chance?
