### ISSUE TITLE
All posts page missing massive numbers of posts

### ISSUE THREAD

**Issue by ben-pace** [LessWrong2/Lesswrong2#2512]
When sorting by yearly, many years are showing 6x and 10x fewer posts than happened, e.g. in 2012 shows ~180 posts but were actually ~2000.

**Comment by jimrandomh** [comment]
A migration script was written in https://github.com/LessWrong2/Lesswrong2/pull/2179 which would have fixed this, but it never got run. (It wasn't written on the "outstanding migrations" list on the whiteboard, nor was there a GitHub issue to track it). @Discordius should be running the migration script today, after which the missing posts should appear.

**Comment by Discordius** [comment]
Fixed after running the "fixMaxBasescore" migration
