### ISSUE TITLE
Post hover preview doesn't show text if post contained LaTeX

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#2518]
If a post contains LaTeX, it starts with a (hidden) LaTeX stylesheet. When the hover-preview produces a truncated version, it counts length incorrectly, including the characters from this stylesheet (even though it will get stripped out at a later stage). As a result, the hover-preview for many posts is just "...".

**Comment by Discordius** [comment]
Ah, cool. I noticed that myself. 

Fix should just be to strip out the stylesheet earlier on?

**Comment by jimrandomh** [comment]
Was fixed in https://github.com/LessWrong2/Lesswrong2/pull/2520 .
