### ISSUE TITLE
Fonts in "Just Another Day in Utopia"

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#2593]
https://www.lesswrong.com/posts/sMsvcdxbK2Xqx8EHr/just-another-day-in-utopia has a bunch of overridden styling left over from the old-LW import, which gives it worse fonts than the rest of the site. The same issue applies to its sequel, https://www.lesswrong.com/posts/Ybp6Wg6yy9DWRcBiR/the-adventure-a-new-utopia-story .

**Comment by Raemon** [comment]
fixed
