### ISSUE TITLE
Self referential pingback at EAForum

### ISSUE THREAD

**Issue by edoarad** [LessWrong2/Lesswrong2#2659]
[This page](https://forum.effectivealtruism.org/posts/3HaXa7dtu86NQNEZJ/shic-will-suspend-outreach-operations) has itself in the list of pingbacks. It does link to itself (various times, using [i] footnotes).

**Comment by jpaddison3** [comment]
I believe this has been fixed by #2613

**Comment by edoarad** [comment]
Great :)
