### ISSUE TITLE
Cannot view site with Firefox reader functionality

### ISSUE THREAD

**Issue by haadr** [LessWrong2/Lesswrong2#273]
When opening an article (ex. https://www.lesserwrong.com/posts/zsG9yKcriht2doRhM/inadequacy-and-modesty) with Firefox (both mobile and desktop) the reader view isn't available. When forcing the reader view with `about:reader?url= ` the message "Failed to load article from page" is displayed.

I use this functionality a lot since the formatting is usually simplified, the Firefox reader mode features a night mode and it will be saved offline for later.

**Comment by Discordius** [comment]
Yeah, there are also some problems with the safari reader (see #63). I would guess the solutions are related.

**Comment by haadr** [comment]
Seems fixed for me on Firefox (android and desktop)! 
Thanks a lot!
