### ISSUE TITLE
Doesn't work with Firefox v. 29

### ISSUE THREAD

**Issue by Cerebrum2** [LessWrong2/Lesswrong2#281]
With Firefox 29 neither the menu on the left side nor the login functionality works.

**Comment by jimrandomh** [comment]
Firefox 29 is from May 2014, so no one should be using a version that old. I tested on the latest version (61.0.1) and the side menu and login seemed to be working fine.

**Comment by meteorplus** [comment]
Doesn't work with Firefox v5 either
