### ISSUE TITLE
Indenting formatted text removes formatting from the first letter of each section of formatting

### ISSUE THREAD

**Issue by ben-pace** [LessWrong2/Lesswrong2#287]
If I have a text with italicised or bolded words/sections, when I use > - 'space' to indent it (i.e. as a quote), each section with formatting _loses formatting on the first letter_. For example,

**bold** _italics_

becomes

b**old** i_talics_

(It seems github isn't reading the in-word italics marker, probably because it messes up website addresses with multiple underscores. Anyway, you know what it would look like.)

**Comment by jimrandomh** [comment]
Doesn't replicate, and we've changed editor framework since this was reported.
