### ISSUE TITLE
[question] Discoverability of this repo

### ISSUE THREAD

**Issue by nlacombe42** [LessWrong2/Lesswrong2#3148]
Should this repo be listed here? https://www.lesswrong.com/faq#I_have_feedback__bug_reports__or_questions_not_answered_in_this_FAQ__What_should_I_do_

So that people can open issues for bugs or feature requests?
Or should all such requests be done through communication to the lesswrong team via Intercom on the main website?
If such requests should be sent through Intercom, I think it would be prefferable to update this repo's README to reflect the instructions shown on the lesswrong website at the URI above.

**Comment by Discordius** [comment]
Good point, I just added it to that list.
