### ISSUE TITLE
We are creating far too many post-view events (2.5M so far)

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#315]
Not sure why, but we are tracking too many post-view events, which is clogging up our DB. We probably want to fix that, and then delete all but the most recent ones for all users.

**Comment by Raemon** [comment]
It's the mechanism by which we mark unread comments on a post, whether a
post is read, etc (as well as just tracking page views, which admins use to
sanity-check some things)

We have some plans to eventually replace some of this with a smaller
document type (UserPostRelation) which just stores all the meta-data in one
place, but it's a significant shift in how some parts of the site would
work.
ᐧ

**Comment by Discordius** [comment]
I think this is actually just fine, now that we moved to a higher DB tier in our provider, and we are miles away from this being a key performance bottleneck. Closing for now.
