### ISSUE TITLE
Tag hover-preview doesn't close when clicking through link on tag page to another tag page

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#3161]
When there's a tag link on a tag page, if you click on the tag, the hover-preview stays open (but loses its positioning) when it should close.

The root cause is probably React reusing a portion of the component tree that ought to be discarded/recreated. In particular, the component trees of two tag pages are isomorphic enough that the `ContentItemBody` of the description could get reused, preserving state that ought not to have been preserved.

**Comment by Raemon** [comment]
Oli suggested adding a key, which I tried, and which seems to fix it: https://github.com/LessWrong2/Lesswrong2/pull/3162

**Comment by Raemon** [comment]
Ah, looks like we made a fix at about the same time. I'm not actually sure which one is conceptually better. 

https://github.com/LessWrong2/Lesswrong2/pull/3164
