### ISSUE TITLE
CkEditor crashes in Firefox Mobile

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#3185]
On Firefox Mobile, CkEditor crashes (on lesswrong) with `Erorr: TypeError: n is undefined`. This affects both the post and comment submission forms, which don't work at all, even enough to switch the editor-type to draftjs.

Here is the error in Sentry: https://sentry.io/organizations/lesswrong/discover/lesswrong:770a6ccdd7ec4b68b96d26a7a121b9d9/?environment=production&field=title&field=event.type&field=project&field=user&field=timestamp&name=All+Events&project=1301611&query=&sort=-timestamp&statsPeriod=24h&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1

┆Issue is synchronized with this [Trello card](https://trello.com/c/K72df4md) by [Unito](https://www.unito.io/learn-more)

**Comment by jimrandomh** [comment]
I tried reproducing this on BrowserStack so I could get a real stack trace, and Firefox-on-Browserstack seems like it just completely failed to execute our Javascript at all (much worse than Firefox-on-my-phone).

**Comment by Discordius** [comment]
Can't reproduce this. Works fine on localhost using browserstack: 

https://live.browserstack.com/dashboard#os=android&os_version=10.0&device=Samsung+Galaxy+S20&device_browser=firefox&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.lesswrong.com%2F&speed=1&host_ports=google.com%2C80%2C0

**Comment by Discordius** [comment]
Ah, I can reproduce this for post forms but not comment forms. Will look into it.

**Comment by Discordius** [comment]
Alas, looks like it's even worse. I don't have any console logs on Browserstack for Firefox mobile, it appears to crash only on lessestwrong and not lesswrong, and doesn't crash on my localhost. So I have no real idea what to do.

**Comment by jimrandomh** [comment]
Fixed in https://github.com/LessWrong2/Lesswrong2/pull/3199 .
