### ISSUE TITLE
using sections later in a post alters vertical space between title and start of text

### ISSUE THREAD

**Issue by zackmdavis** [LessWrong2/Lesswrong2#3245]
![vertical!UNITO-UNDERSCORE!space](https://user-images.githubusercontent.com/1076988/83961345-efa58280-a846-11ea-9326-be32c4570ea2.png)

I was going to have a `### Bibliography` section at the end of my next post, but it seems that including any sections in a post, changes the vertical spacing between the headline and the start of the text, in a way that I think is ugly. ([It looks better when](https://www.lesswrong.com/posts/irbREZtZzPi7WEYex/book-review-human-compatible-1) there's a section heading at the _start_ of the post.) I hoped I could work around it by using a standalone bolded paragraph (`**Bibliography**`), but the section-detection code is too smart and counts that as a section. As a workaround, I'm just going to use a horizontal rule (`-----` [graf break] `_Bibliography_:`), but I thought I might as well file this issue, too.

┆Issue is synchronized with this [Trello card](https://trello.com/c/jQMh1KQf) by [Unito](https://www.unito.io/learn-more)

**Comment by Discordius** [comment]
Fixed in #3246. 

Thanks for reporting this!

**Comment by zackmdavis** [comment]
Has this been deployed? https://www.lesswrong.com/posts/fmA2GJwZzYtkrAKYJ/algorithms-of-deception still has the large gap.

**Comment by Discordius** [comment]
Don't think so. We haven't deployed in a while because of some risky changes in staging. But will probably go live next week.
