### ISSUE TITLE
Try out full story

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#328]

**Comment by jimrandomh** [comment]
What is this referring to?

**Comment by patbl** [comment]
I think it's referring to [Fullstory](https://www.fullstory.com/), a product for capuring videos of users interacting with the site. It can be useful for debugging or for diagnosing usability problems. You can filter the recorded sessions using various metadata (user ID, URLs that match a regex, etc.).

The free plan records 1,000 sessions per month, and the $299 plan records 25k sessions per month. So if you were to use it, you'd probably need to restrict it to whatever pages we think are most valuable or buggy, and then record a subset of them.

**Comment by Discordius** [comment]
Yep, Eric Rogstead used it while working on Arbital and was very excited
about it, and strongly recommended trying it out sometime.
