### ISSUE TITLE
API error when undoing a vote

### ISSUE THREAD

**Issue by kronusaturn** [LessWrong2/Lesswrong2#3433]
When trying to remove a vote on a post or comment, the LW API returns the error:

> Cannot read property 'newDocument' of undefined

I'm using the following GraphQL statement:

> mutation vote($documentId: String, $voteType: String, $collectionName: String) { vote(documentId: $documentId, voteType: $voteType, collectionName: $collectionName) { ... on Post { baseScore, af, afBaseScore, currentUserVotes { _id, voteType, power } } ... on Comment { baseScore, af, afBaseScore, currentUserVotes { _id, voteType, power } } } }
```

**Comment by Discordius** [comment]
Fixed in https://github.com/LessWrong2/Lesswrong2/pull/3436

**Comment by jimrandomh** [comment]
Note that while the old API is still there and will be supported for as long as anyone's using it, https://github.com/LessWrong2/Lesswrong2/commit/4cc4753d19648076805dccb07c1b613d3c8ac65e adds a new API that should be simpler to work with. The new API, `setVotePost`/`setVoteComment`/`setVoteTagRel`, takes the vote you want to cast (or null to remove your vote). This moves all the button-toggling logic out of the API and into the frontend where it belongs, so if you upvote in one tab, switch to a different tab, and upvote there, it no longer cancels your vote by surprise.
