### ISSUE TITLE
502 Bad Gateway error when retrieving a tag

### ISSUE THREAD

**Issue by kronusaturn** [LessWrong2/Lesswrong2#3434]
Running the following query:

> {tag(input:{selector:{slug:"rationality"}}){result{_id}}}

results in a 502 Bad Gateway error.

**Comment by Discordius** [comment]
When I run that error I get the following server error: 

`Assertion failed: (!h.IsEmpty()), function Unmaybe, file ../src/bson.h, line 60.`

This is likely related to the `bson-ext` library we are using. @jimrandomh, you probably have some thoughts.

**Comment by Discordius** [comment]
Besides that happening, the thing that's going on is that we don't currently support querying by slug for most collections, and the above is somehow ending up in an untested codepath that sadly doesn't throw very useful errors. We should definitely fix that, but until we support querying by slug for tags, you will anyways have to do the same thing we do, which is to send something like the following query: 

```
query multiTagQuery($input: MultiTagInput) {
  tags(input: $input) {
    results {
      ...TagFragment
      __typename
    }
    totalCount
    __typename
  }
}

fragment TagFragment on Tag {
  ...TagBasicInfo
  description {
    html
    htmlHighlight
    plaintextDescription
    __typename
  }
  __typename
}

fragment TagBasicInfo on Tag {
  _id
  name
  slug
  oldSlugs
  core
  postCount
  deleted
  adminOnly
  defaultOrder
  suggestedAsFilter
  needsReview
  reviewedByUserId
  descriptionTruncationCount
  wikiGrade
  __typename
}
```

**Query variables:**

```
{
  "input": {
    "terms": {
      "view": "tagBySlug",
      "slug": "world-optimization",
      "limit": 1
    },
    "enableCache": false,
    "enableTotal": false
  }
}
```

**Comment by kronusaturn** [comment]
Is querying tags by slug no longer supported due to an intentional change? It worked until a few weeks ago.

**Comment by Discordius** [comment]
Yeah, we changed that when we implemented forwarding of old slugs. I.e. previously it was just a simple query on the `slug` datafield, but now it's also querying the `oldSlugs` field, which is the array of all previous names that this slug had.

**Comment by Discordius** [comment]
It is definitely not intentional though to have everything just crash, so I am treating this as a regression. Let me see whether I can fix the `querying the slug` directly use-case, even if it isn't what I think makes sense to use.

**Comment by Discordius** [comment]
Fixed in: https://github.com/LessWrong2/Lesswrong2/pull/3437
