### ISSUE TITLE
RSS feed links are broken

### ISSUE THREAD

**Issue by aarongertler** [LessWrong2/Lesswrong2#3480]
Links generated in the "Subscribe (RSS)" part of the sidebar are broken. Here's an example:

https://forum.effectivealtruism.orgfeed.xml?view=frontpage-rss&karmaThreshold=30

There's a missing "/" between "org" and "feed". If you add that manually, you get a correct-looking page of RSS stuff. The "/" is missing for every "number of posts" option.

**Comment by jpaddison3** [comment]
Only affects the forum, will be fixed by today's deploy.
