### ISSUE TITLE
CkEditor: Range-deleting multiple paragraphs leads to corrupt state

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#3565]
In CkEditor, create four paragraphs, like this:
```
1

2

3

4
```
Place the cursor before the '4'. Shift-select after the '1' to create a selection that includes paragraphs 2 and 3 and all of the paragraph-dividers. Press backslash. The result should be:
```
14
```
but instead it's
```
13

4
```
Now press Cmd+Z to undo what you just did. The result should have all four paragraphs, but instead it's
```
1

2

4
```
(paragraph 3 is missing)

**Comment by Discordius** [comment]
Indeed, can confirm. Pretty surprising I haven't run into this before.

**Comment by Discordius** [comment]
Will leave a bug report on the CKEditor repo

**Comment by Discordius** [comment]
https://github.com/ckeditor/ckeditor5/issues/8219

**Comment by Discordius** [comment]
Fixed in: https://github.com/ckeditor/ckeditor5/issues/8145

Will upgrade whenever the next major release comes out.
