### ISSUE TITLE
No Content-Type for feed.xml

### ISSUE THREAD

**Issue by kevinoid** [LessWrong2/Lesswrong2#3619]
The HTTP response for https://www.lesswrong.com/feed.xml does not currently include a [Content-Type header](https://tools.ietf.org/html/rfc7231#section-3.1.1.5):

    $ curl -I https://www.lesswrong.com/feed.xml
    HTTP/2 200 
    date: Sat, 31 Oct 2020 13:32:39 GMT
    set-cookie: AWSALB=KdhwbExnYP6rHyOnTkdbne+wC968n0jYbHvbIHUe4oBCRtigzoch7aMvRBMo8Vsg5WQ3R/L8aL0a/2Y0NWOD+9qz+RBI318NKB+OrqzX3GBuT+GmJ+Avubh+foHt; Expires=Sat, 07 Nov 2020 13:32:39 GMT; Path=/
    set-cookie: AWSALBCORS=KdhwbExnYP6rHyOnTkdbne+wC968n0jYbHvbIHUe4oBCRtigzoch7aMvRBMo8Vsg5WQ3R/L8aL0a/2Y0NWOD+9qz+RBI318NKB+OrqzX3GBuT+GmJ+Avubh+foHt; Expires=Sat, 07 Nov 2020 13:32:39 GMT; Path=/; SameSite=None; Secure
    server: nginx/1.12.1
    strict-transport-security: max-age=31536000; includeSubDomains;
    
This can confuse RSS readers and browser addons which must perform content sniffing to determine the type and charset.  Sending `Content-Type: `[`application/rss+xml`](https://tools.ietf.org/html/draft-nottingham-rss-media-type-00) or generic [`application/xml`](https://tools.ietf.org/html/rfc7303) (with or without the `charset=utf-8` optional parameter) might cause fewer issues.

Thanks for considering,
Kevin

**Comment by jimrandomh** [comment]
Fixed the header not getting set at all in https://github.com/LessWrong2/Lesswrong2/commit/aca7e20f628a6ef09c1a3f341acee25a4dbc3cc2 , and set the character set to UTF-8 properly in https://github.com/LessWrong2/Lesswrong2/pull/3707 .

**Comment by kevinoid** [comment]
Looks great.  Thanks @jimrandomh!
