### ISSUE TITLE
glitchy voting behavior (graphql?)

### ISSUE THREAD

**Issue by gwillen** [LessWrong2/Lesswrong2#3621]
I am having an odd issue with voting on comments on this post https://www.lesswrong.com/posts/osYFcQtxnRKB4F4HA/a-tale-from-communist-china -- when I vote on a comment, the vote appears, but then immediately disappears, but if I refresh the page it reappears. ~~At the network level, I see a graphql mutation to add the vote, which gets a response that says it worked; then I get another graphql request with a response that gives the old vote total again.~~ [see below, I think this was an error on my part.] (Then refreshing the page, I see actually it worked after all.) It seems to happen to me on every comment on that page, but not on other pages I tried.

**Comment by gwillen** [comment]
Actually, now I'm not 100% sure I correctly reported what I saw before. When trying to _unvote_ now, what I seem to see: Each click sends a toggle message to the server, which correctly responds with toggled state (that is, every alternate response is either showing the comment score go back down to 2, or showing it go back up to 4 with my vote present). But the client in each case shows the comment drop down to 2 for a moment, then go back up to 4, as though it has failed to understand the response.

(It seems bad to me that your vote request is a toggle rather than a set. I have run into glitchy voting behavior before, and now I see that it's probably related to this bug. It's never been _persistent_ before -- usually it seems like a single state update gets lost, the client gets confused about the state of the vote, but if I large-vote and then small-vote it will get unconfused. I think in general it is quite common for your client and server code to get desynchronized about what the vote state of an object is.)

**Comment by gwillen** [comment]
I suspect the problem with this specific page is that somehow the client is confused about the page ID, so that every graphql response it gets seems to pertain to some nonexistent object and is discarded (and then the client undoes the temporary vote it applied while waiting for the server's response.) Meanwhile the server happily toggles the vote with each request, but the client has no idea (and reports no error to the user.)

**Comment by Discordius** [comment]
> (It seems bad to me that your vote request is a toggle rather than a set. I have run into glitchy voting behavior before, and now I see that it's probably related to this bug. It's never been persistent before -- usually it seems like a single state update gets lost, the client gets confused about the state of the vote, but if I large-vote and then small-vote it will get unconfused. I think in general it is quite common for your client and server code to get desynchronized about what the vote state of an object is.)

Yeah, that is a horrible architecture decision we inherited from the framework we started from. It's caused its fair share of bugs, and I expect we will eventually change it. 

Re. the higher level bug: Yeah, I noticed this behavior as well on another post. It doesn't have anything to do with the pageId, and indeed what is happening is pretty weird and I haven't yet figured out what exactly is happening.

**Comment by gwillen** [comment]
Hmm, it's not even all comments on that page, it's all descendants of https://www.lesswrong.com/posts/osYFcQtxnRKB4F4HA/a-tale-from-communist-china?commentId=HrkdZKhkerPEF7NiH . (That comment only has one child, so I can't tell if it's "all descendants of that comment, exclusive" or "all descendants of its child comment, inclusive.")

**Comment by jimrandomh** [comment]
There were a couple related issues here. One is that there was a period in which the client-side display of votes was broken; ie, you'd click the vote button and it would register on the server, but it wouldn't be visible on the client until you refreshed. That one is fixed in https://github.com/LessWrong2/Lesswrong2/pull/3664 . The other is that the message sent to the server was a "toggle" message, so if it failed to update properly on the client (or you went to another tab), and you pushed the button again, it would remove the vote that you wanted to add. That's fixed in https://github.com/LessWrong2/Lesswrong2/pull/3648/commits/4cc4753d19648076805dccb07c1b613d3c8ac65e ; now the API sends what you want the vote-state to be, so if you upvote something, go to another tab without refreshing, and upvote it again, the final result is that you've upvoted it as expected.
