### ISSUE TITLE
Registration link broken

### ISSUE THREAD

**Issue by DreamFlasher** [LessWrong2/Lesswrong2#363]
When I click on "sign up" nothing happens (Chrome, Firefox). Same for "forgot password".

**Comment by Kronopath** [comment]
I also have this issue.

**Comment by Discordius** [comment]
@Kronopath: I fixed this bug a week ago, can you let me know what precisely you are running into?

**Comment by Kronopath** [comment]
It's exactly what the poster above says. I go to the front page, click "Log in", click "Sign up", enter a suitable username, email, and password, click "Sign up", and… nothing happens. 

I managed to fix it, though. Here's what I think happened:
1. Last week, I tried to make an account, but the feature was broken.
2. However, in your system, it actually *did* register an account… with no password, making it impossible to log in.
3. I had initially tried to use the the "forgot password" utility, but I was using an email address *different* from the one that I had initially created that broken account with. When I changed the email address to the correct one, I managed to receive the password reset link.

Below is how I diagnosed the issue. Skip to the bottom if you're not interested in the details.

-----------

I did a bit of digging with the inspectors in different browsers. The Chrome inspector runs into a GraphQL error and *hangs* when trying to display a huge minified file. The Firefox inspector was more helpful.

Attempting to sign up with the same username that I have here at Github, and a suitable email and password, spits out a GraphQL error in the Firefox inspector, saying `"Username already exists [403]"`. 

Attempting to log in with that same username and password gave me another error, `"User has no password set [403]"`.

Attempting to reset my password with what I *thought* was the correct email led to a `"User not found [403]"` error. That's what led me to realize that maybe I was using the wrong email address, and doing the same thing with the correct one worked.

---------

The problems here are twofold:

1. Some people who tried to sign up while this feature was broken might end up like my account did, with the account existing but with no password set. It might be worth looking for any users that did this and forcing a password reset.
2. *None* of these errors, such as having an incorrect username or email, trying to register a duplicate account, etc. are actually shown to the user. The operation just fails *silently*, leaving the user to think that something is broken. This is the biggest problem here, and I don't know whether it's a bug or a feature that's currently unimplemented.

**Comment by DreamFlasher** [comment]
@Discordius Doesn't work for me. I do exactly what I wrote in my first comment and it doesn't work. Can you give it a try and look at the page itself to verify that it works for you to create a new user?

**Comment by Discordius** [comment]
Ok, now I get it. There is a bug that only shows up in production (yay, my favorite kind of bug), where the error messages for the sign up form disappear. I added an issue on Github for Vulcan: 
https://github.com/VulcanJS/Vulcan/issues/1888

I hope I can fix it soon. For now try to experiment with other usernames and longer passwords (and maybe different email addresses)
