### ISSUE TITLE
Posts are greyed out after selecting "Show Low Karma" 2 times

### ISSUE THREAD

**Issue by mduczmal** [LessWrong2/Lesswrong2#3695]
### Description
Posts are greyed out after selecting _Show Low Karma_ multiple times on `/allPosts`. This happens for every timeframe different from _All time_.

### Example
![greyed_out](https://user-images.githubusercontent.com/20318304/99900025-d174f700-2cad-11eb-87ee-3cd4f835f17e.png)

### Steps to reproduce
1. Go to _All Posts_.
2. Click the gear icon.
3. Select _Show Low Karma_.
4. Deselect _Show Low Karma_.
5. Select _Show Low Karma_.

### Browsers
I observed this behavior using Firefox 83.0 and Chrome 86.0.4240.183.

**Comment by Discordius** [comment]
Indeed, weird. Will look into it.
