### ISSUE TITLE
502 Bad Gateway error on LWUsersAdmin view

### ISSUE THREAD

**Issue by riceissa** [LessWrong2/Lesswrong2#3711]
I am using [this](https://www.lesswrong.com/graphiql?query=%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20users%28input%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20terms%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20view%3A%20%22LWUsersAdmin%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20limit%3A%20500%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20sort%3A%20%7Bkarma%3A%20-1%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20results%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20_id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20slug%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20karma%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20postCount%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20commentCount%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20afKarma%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20afPostCount%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20afCommentCount%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20) query to populate the [userlist page](https://lw2.issarice.com/userlist?sort=karma) (currently blank due to this error) on my LW reader. The [corresponding query](https://forum.effectivealtruism.org/graphiql?query=%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20users%28input%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20terms%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20view%3A%20%22LWUsersAdmin%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20limit%3A%20500%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20sort%3A%20%7Bkarma%3A%20-1%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20results%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20_id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20slug%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20karma%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20postCount%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20commentCount%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20afKarma%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20afPostCount%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20afCommentCount%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20) for EA Forum works, and the [userlist page](https://eaforum.issarice.com/userlist?sort=karma) also displays as intended.

I tried looking for a different view to use, but I couldn't find one that could return a list of users sorted by various attributes (e.g. karma, post count, comment count).

I thought this issue was the same as https://github.com/LessWrong2/Lesswrong2/issues/3434 but that is now closed (and I don't get the 502 error on the query listed there).

**Comment by jimrandomh** [comment]
The query works on my local install connected to the production DB, but fails on lesswrong and lessestwrong with 502 Bad Gateway. It does not log any clues in Sentry. Removing the sort option makes the query work; shrinking the limit or trimming the result fields does not.

**Comment by jimrandomh** [comment]
Seems to be fixed on lessestwrong (our staging server) now, so it should be fixed on production the next time we deploy.
