### ISSUE TITLE
Seeing future days on all posts

### ISSUE THREAD

**Issue by jecneps** [LessWrong2/Lesswrong2#373]
It's sunday 8:18pm Feb 4, and when I refresh the all posts feed, Monday momentarily pops up (along with alkjash's next hammertime post, but then promptly disappears. I'm guessing we have a "shedule your post for the future" ability, but it's leaking through?

**Comment by Discordius** [comment]
This is actually a timezone issue, where sometimes not all content shows on the daily page, and it's a giant pain to debug because I hate timezones. So you don't actually see posts scheduled into the future, but instead don't see some posts that have been normally posted, which is even worse.

**Comment by jecneps** [comment]
Ow, yeah, timezones == terrible. Good luck.

**Comment by Discordius** [comment]
Should be fixed after timezone adjustments
