### ISSUE TITLE
The Cancel Reply button opens commenting guidelines instead

### ISSUE THREAD

**Issue by tdnzr** [LessWrong2/Lesswrong2#3820]
I frequently accidentally click the Reply button, then try to cancel out of the reply menu, only to see the Commenting Guidelines first (the same thing happens when you click Submit, but I expect it's intentional there); I need to click a superfluous second time to actually cancel.

3-second [video](https://drive.google.com/file/d/1RcepKyEz4uxfr4V0xiRtFX0x5n5aEfmW/view?usp=drivesdk)

**Comment by jimrandomh** [comment]
Fixed in upcoming release
