### ISSUE TITLE
New tag is displayed as "Name"(null)

### ISSUE THREAD

**Issue by mateuszkocik** [LessWrong2/Lesswrong2#3845]
### Description
New tag is displayed as "Name"(null) instead of "Name"(0)
### Steps to reproduce
1. Select from left-side menu "Concepts"
2. Scroll down to "All tags" section
3. Click "New Tag" button
4. Fill name in "Name" field
5. Select "Submit" button
6. Return to "All tags" section
### Example
![tagnull1](https://user-images.githubusercontent.com/72257575/104136334-b8c3bc00-5395-11eb-8fb1-a1d76de0343f.png)

**Comment by jimrandomh** [comment]
Fixed in upcoming release
