### ISSUE TITLE
a.PostLinkPreviewWithPost-link::after asterisk misplaced

### ISSUE THREAD

**Issue by davgross** [LessWrong2/Lesswrong2#3869]
The asterisk that is added by the `a.PostLinkPreviewWithPost-link::after` pseudoelement often moves vertically away from its intended position.
**[Example:](https://www.lesswrong.com/posts/WxRGSgNj5dmQ7mBmK/notes-on-courtesy)**
![image](https://user-images.githubusercontent.com/5952946/104784729-c1bde000-573d-11eb-8aca-a65cc682c351.png)

I can fix this by turning off the `position: absolute` style for that pseudoelement, but I don't know if perhaps that breaks something else somewhere.
Linux/Firefox 84.0.2

**Comment by Discordius** [comment]
Wow, that sure is a screenshot. I think this tends to happen more on Firefox, but yeah, we should definitely fix this.

**Comment by davgross** [comment]
Possible duplicate of #3186

**Comment by jimrandomh** [comment]
https://github.com/LessWrong2/Lesswrong2/pull/3968
