### ISSUE TITLE
Comment email notification links broken?

### ISSUE THREAD

**Issue by gwillen** [LessWrong2/Lesswrong2#3957]
See https://www.lesswrong.com/posts/nMNi86hgNjaNnh8iu/a-whirlwind-tour-of-ethereum-finance?commentId=5oeGEdwqBtBndLSeA .

When I got notified about comment `8EWhzfjs82qcJyAkC`, the email contained the link `http://email.mg.lesserwrong.com/c/eJyFj0FrxCAYRH-NuRkSTVw9eFi6u9BCc-3Z6md0m-hWDdL--tpLr4WBgcfwYIxUloiJdl6ykQgy6wEDvAtsxQSYaS2wIXY0VmlFtEDTsEHOkGqKYe113Dsn6UwGY82omWBkMhOn5sRPnOgBBNiZdZt0pTwyomdEbi211v5X8ydp7P_FI-aSW4fXxXPm1uWuluC4PxpTuDqftuqDwSUeCUeLoThIcOzY-qCCBkRvTbRDKM8G0Qu_vrlve8-cfOqXr_PHU5fkWv22QWgvAyQToPQxrT8j4l_r`, which serves a redirect to `https://www.lesswrong.com/https://www.lesswrong.com/posts/nMNi86hgNjaNnh8iu/a-whirlwind-tour-of-ethereum-finance?commentId=8EWhzfjs82qcJyAkC`. Note the broken redirected URL (it contains the scheme and domain twice.)

**Comment by gwillen** [comment]
Going back through my inbox, the breakage seems to have happened (or at least to be affecting notifications starting) sometime between 2/23 and 2/25.

**Comment by Discordius** [comment]
Yep, I noticed this yesterday too.

**Comment by jimrandomh** [comment]
Fixed in https://github.com/LessWrong2/Lesswrong2/pull/4048
