### ISSUE TITLE
Tag-links with post-counts have no space between tagname and count

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#4031]
This looks quite ugly to me: 

![image](https://user-images.githubusercontent.com/9090789/115628119-f9947080-a2b4-11eb-933a-da9f40aa6781.png)

And I am pretty sure looked quite different recently? Should be just a one-line CSS change to fix.

**Comment by darkruby501** [comment]
The the lack of space is definitely new.

**Comment by jimrandomh** [comment]
Fixed in 22959427b1c23e259de139dbb555c891e8fddc43 . (But, note: you put a margin there instead of a space, which messes up copy-paste and maybe screenreaders. It's not a big deal in this case, but seems to be a bad habit.)
