### ISSUE TITLE
tag grading link returns an error

### ISSUE THREAD

**Issue by benthamite** [LessWrong2/Lesswrong2#4036]
The second [ETA: and also the first] link under the question [What is a tag's quality grade](https://www.lesswrong.com/posts/E6CF8JCQAWqqhg7ZA/tagging-faq#What_is_a_tag_s_quality_grade_) in the Wiki-Tag FAQ returns `Error: app.operation_not_allowed`.

**Comment by jimrandomh** [comment]
@darkruby501

**Comment by Discordius** [comment]
I undrafted the relevant post. We can redraft them if we realize there was a good reason for them to be drafted and we need to change something bigger.
