### ISSUE TITLE
Problem with search results that are comments

### ISSUE THREAD

**Issue by ksvanhorn** [LessWrong2/Lesswrong2#416]
When I do a search, clicking on any result that is a comment just gives me an error message saying it can't find the page.

**Comment by movationdesign** [comment]
Yeah, I can confirm this problem is still there.

**Comment by Raemon** [comment]
Huh – not sure whether I'm correctly understanding this (it's possible we partially fixed this in the past two months)

What I currently experience is that:

1) It correctly goes to a page with the comment, but
2) It has to scroll down to see the comment (which requires loading the comments)
3) many old posts have a _lot_ of comments (and it seems like the search bar sort of disproportionately selects comments on posts with more comments?), which makes for huge load times.

I think this is a different problem than what ksvanhorn was originally reporting (which may have been a chunk of time when we had changed how comment links worked)
