### ISSUE TITLE
Failures produce no error message

### ISSUE THREAD

**Issue by ksvanhorn** [LessWrong2/Lesswrong2#417]
If you try to log in and you can't, nothing happens. No error message, nothing. If you click on "Load more" in the "Recent Comments" section of a user profile, and there is nothing more to load, nothing happens -- no error message. (And why does it say "load more" if there is no more?)

**Comment by ksvanhorn** [comment]
Ditto for trying to reset my password. It finds my name from my email, but when I click "Reset your password," all that happens is I get some special-effects stuff happening on the button. Absolutely nothing else happens.

**Comment by jimrandomh** [comment]
Failed logins: Error messages are shown now.

Reset password: Seems to show appropriate error messages now. (Caveat in #821).

"Load more" in "Recent Comments" on user profiles when there are no more comments: Still broken. Making a separate issue for that (#823).
