### ISSUE TITLE
"Alignment Options" dropdown when editing comment

### ISSUE THREAD

**Issue by gwillen** [LessWrong2/Lesswrong2#4186]
When I edit a comment on LessWrong, I have started getting a box in it that says "Alignment Options" and lets me pick a username. I assume this is exposing some part of the data model (I guess related to Alignment Forum?) that is not meant to be exposed to me.

**Comment by gwillen** [comment]
<img width="722" alt="Screen Shot 2021-09-14 at 3 54 44 PM" src="https://user-images.githubusercontent.com/458997/133344381-42fd7e85-ba3d-49f5-af5a-a8b6cfbaa11b.png">

**Comment by Discordius** [comment]
Oops, should be fixed in: https://github.com/LessWrong2/Lesswrong2/pull/4187
