### ISSUE TITLE
Link in the readme leads to phishing site

### ISSUE THREAD

**Issue by Kuratius** [LessWrong2/Lesswrong2#4194]
Specifically the one about telescope

**Comment by jimrandomh** [comment]
Fixed in https://github.com/LessWrong2/Lesswrong2/commit/073fc71e4c3cf73c9a6f69528a2b15c8df564b7e

**Comment by Kuratius** [comment]
You could also link an internet archive backup, if you wanted https://web.archive.org/web/20200126163840/http://www.telescopeapp.org/blog/using-telescope-as-a-reddit-alternative/
