### ISSUE TITLE
Lesserwrong breaks under Firefox's Tracking Protection

### ISSUE THREAD

**Issue by dannyob** [LessWrong2/Lesswrong2#428]
I had to turn off Firefox's tracking protection to log into Lesserwrong on the latest Nightly; I don't _think_ it's turned on by default, but I've rarely had problems with websites breaking with it on (this is the first one I can recall turning it off for), and it was a bit hard to spot that this was the problem -- it looked like a lesserwrong problem until I tried to find out what the bug was to report it.

It may be worth trying to do a walkthrough of signing up/logging on the site with TP on, just to see if you can put a warning in at the appropriate moment. Or do the fixing that's needed to make sure the site does work.

Thank you for all your efforts!

**Comment by lordcirth** [comment]
I cannot login either, but my Tracking Protection is set to "only on Private windows", so it doesn't seem to be that.  I've tried exempting it from Privacy Badger and uBlock Origin, but that didn't help either.

**Comment by jimrandomh** [comment]
I wasn't able to reproduce this with the most recent version of the site and of Firefox, with tracking protection set to "Always".
