### ISSUE TITLE
Cannot create account: Internal server error [500]

### ISSUE THREAD

**Issue by chkno** [LessWrong2/Lesswrong2#474]
When I try to create an account, I get the red text "Internal server error" and an account is not created.  

POST to https://www.lesserwrong.com/sockjs/718/16vs5xpo/xhr_send
{
  "msg":"method",
  "method":"createUser",
  "params":[{
    "username":"chkno",
    "email":"chkno@chkno.net",
    "password":{
      "digest":"06907fc29fc38535fb1665bf65b72fe9857457955611de594fae32e15e1db10b",
      "algorithm":"sha-256"
    }
  }],
  "id":"1"
}

(200) Response from a POST to https://www.lesserwrong.com/sockjs/718/16vs5xpo/xhr
{
  "msg":"result",
  "id":"1",
  "error":{
    "isClientSafe":true,
    "error":500,
    "reason":"Internal server error",
    "message":"Internal server error [500]",
    "errorType":"Meteor.Error"
  }
}

I did not receive a confirmation email and the "Forgot password" mechanism says "User not found"

**Comment by Discordius** [comment]
Ah, there was a problem with the error messages. This happened when we already had a user with the same username.
