### ISSUE TITLE
LessWrong 1.0 URLs with comment anchors don't point to the intended comment

### ISSUE THREAD

**Issue by riceissa** [LessWrong2/Lesswrong2#484]
LW 1.0 has specific "comment URLs" (the slug after the final `/`) and in addition has "comment anchors" (the optional slug after `#`). It looks like LW 2.0 only has the latter, but uses the former from LW 1.0 to point to a comment. This means if a LW 1.0 URL has both a comment URL and comment anchor, the information contained in the comment anchor is lost.

Some examples to show what I mean:

- http://lesswrong.com/lw/nzp/astrobiology_iii_why_earth/dfyq?context=1#dg24 In LW 1.0, this points to CarlShulman's comment "Primates and eukaryotes would be good" while the comment above it by CellBioGuy is highlighted in yellow. If I go to the corresponding link by replacing `lesswrong.com` with `lesserwrong.com`, I am taken to CellBioGuy's comment at https://www.lesserwrong.com/posts/PJ4RPks9GkWYgdmxx/astrobiology-iii-why-earth#cTSbRieWQKJWLpJ9x and there is no indication that Carl's comment was somehow relevant to the original URL.
- http://lesswrong.com/lw/mrp/a_toy_model_of_the_control_problem/#cr6t should point to CarlShulman's comment starting with "Of course, with this model it's a bit of a mystery why A gave B", but http://lesserwrong.com/lw/mrp/a_toy_model_of_the_control_problem/#cr6t points nowhere on the [new page](https://www.lesserwrong.com/posts/7cXBoDQ6udquZJ89c/a-toy-model-of-the-control-problem#cr6t) (the scrolling just stays at the top).
- http://lesswrong.com/lw/mrp/a_toy_model_of_the_control_problem/cr6t#cr7a should point to Kyre's comment, but on LW 2.0 it just [goes to Carl's comment above](https://www.lesserwrong.com/posts/7cXBoDQ6udquZJ89c/a-toy-model-of-the-control-problem#np8eAFyJHm2xgZjtn).

**Comment by Discordius** [comment]
Oh, thanks a lot for letting us know about that. I was totally unaware of that functionality and we should restore it. Do you have any suggestions for what the best way to restore that information in the new LW 2.0 design would be?

**Comment by riceissa** [comment]
For me, it would be most intuitive if it worked basically like LW 1.0. So the LW 1.0 comment anchor would be used to decide where to scroll down to on LW 2.0, and the LW 1.0 comment URL would be used to decide which comment on LW 2.0 to highlight (LW 2.0 currently doesn't do a stable highlight, and I'm not sure how difficult this would be to implement).

Alternatively (to preserve the current "LW 1.0 comment URL = LW 2.0 anchor" relationship), the comment corresponding to the LW 1.0 comment anchor could somehow be marked (perhaps with a background color).
