### ISSUE TITLE
Parsing of links doesn't work

### ISSUE THREAD

**Issue by hrosspet** [LessWrong2/Lesswrong2#487]
E.g. `The author was referencing [Lean product development](https://en.wikipedia.org/wiki/Lean_product_development) and [Agile software development](https://en.wikipedia.org/wiki/Agile_software_development)` parses the first link, but fails on the second

**Comment by Discordius** [comment]
Ah, we only parse markdown after you press space, and can't super easily
parse it when you hit submit.

**Comment by hrosspet** [comment]
Ok, but try it out. Pressing space corrupts the second link.
