### ISSUE TITLE
Some old linkposts don't have links imported

### ISSUE THREAD

**Issue by coriain** [LessWrong2/Lesswrong2#489]
e.g. https://www.lesserwrong.com/posts/BLfFgcPL38ED3poSY/don-t-shoot-the-messenger
![lw-missingpost-grab](https://user-images.githubusercontent.com/2991220/37794195-08aadb5e-2dce-11e8-82b6-6fe36e732a69.png)

Browsers: Chrome, Opera, Firefox & Brave on Windows

**Comment by Discordius** [comment]
Ah, that's a link post, and it looks like the link must have gotten lost. Will fix.

**Comment by Raemon** [comment]
This can be merged with https://github.com/Discordius/Lesswrong2/issues/502, correct?
