### ISSUE TITLE
Meteor JS filesize can be significantly minified (41% reduction)

### ISSUE THREAD

**Issue by movationdesign** [LessWrong2/Lesswrong2#500]
I was just doing some performance tests for LessWrong. According to https://gtmetrix.com/reports/www.lesserwrong.com/VEgqrGXS — the total file size of the Meteor JS file can be reduced with around 672kb (41%). 

Unless I'm reading it wrong, there’s potential to massively improve the initial page load time of LessWrong. What I don't get is why Meteor isn't already minifying that file properly before deployment. 

Or perhaps I'm reading the GTMetrix wrong?

**Comment by Discordius** [comment]
We definitely are using a minifier (the standard meteor minifier), but maybe it isn't catching some of the stuff? I would be very interested in someone trying to minify the code more if there is indeed this much space for improvement, though I currently think gtmetrix is probably just confused.
