### ISSUE TITLE
The comments are form a different post

### ISSUE THREAD

**Issue by jecneps** [LessWrong2/Lesswrong2#518]
I was looking at this post
https://www.lesswrong.com/posts/fpRN5bg5asJDZTaCj/against-occam-s-razor
and then went to this post
https://www.lesswrong.com/posts/fgNtucxwqa7Sa9kKG/reducing-agents-when-abstractions-break
and the comments I was seeing on the second post were the ones from the first. I wasn't able to recreate this bug, but thought I'd mention it.

**Comment by Raemon** [comment]
Okay. Waiting on some more instances of the bug before trying to diagnose this, but good to know.

**Comment by ben-pace** [comment]
Abram just had this problem again. He was in one post, clicked to a second via his notifications, and the second post had the first post's comments.

**Comment by ben-pace** [comment]
Oh, he had clicked on the notification for a comment on the post.
