### ISSUE TITLE
Improve default table styling

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#522]
A bunch of legacy posts have tables, and the tables in them look somewhat broken. Here are some examples: 

https://www.lesswrong.com/posts/AszKwKyhBPZAnCstA/solomonoff-cartesianism
https://www.lesswrong.com/posts/HFyWNBnDNEDsDNLrZ/the-true-prisoner-s-dilemma
https://www.lesswrong.com/posts/zEWJBFFMvQ835nq6h/decision-theory-faq

We can probably fix them by just adding some better padding and spacing to tables by default.

**Comment by berekuk** [comment]
Here's a dilemma:
* Some old posts have tables in them which look bad, and this can be cleaned up with minor CSS; at the same time, old posts often contain a complicated inline styles.
* New markdown posts should include markdown tables (#654), and we want a pretty styling for those.

So we can either:
1. Apply a conservative styling across all tables, but markdown tables would look quite basic.
2. Or we can use more sophisticated styling, with highlighted `<th>` and zebras, but risk that some old posts will look funny.

I'm leaning towards (1), with some simple padding and border for th. PR: #673

Related question: is it possible to distinguish old posts in which HTML markup was allowed? If it's possible, we could pass this info as a flag into a css class and apply different styles for different posts. I tried looking into a few docs in db directly for this but didn't have much luck.
