### ISSUE TITLE
Deleted legacy account is restored and cannot be deleted again

### ISSUE THREAD

**Issue by guzey** [LessWrong2/Lesswrong2#533]
Back when I was 15 I left some pretty embarrassing comments on lesswrong. I deleted that account several years ago, but was able to login on lesswrong2. Full history of comments along with karma, etc. was restored as well. I cannot delete this account right now either, as there's no such option in the account tab and the team has not responded on Intercom for more than a week.

(Possibly related: https://trello.com/c/PdiiTRpr/171-handle-case-when-users-creates-comment-or-post-and-then-deletes-their-own-account)

**Comment by Discordius** [comment]
Ah, just stumbled across this. If you send us another ping on Intercom with your username, we can look into it.

**Comment by jimrandomh** [comment]
@Discordius Did this get resolved?

**Comment by Discordius** [comment]
Yep, this should now be resolved.
