### ISSUE TITLE
Can't subscribe to RSS feed in Feedly

### ISSUE THREAD

**Issue by patbl** [LessWrong2/Lesswrong2#578]
I got this link by hovering over "Frontpage Posts" and clicking "Create an RSS Feed":

https://www.lesswrong.com/feed.xml?view=frontpage-rss&karmaThreshold=0
![image](https://user-images.githubusercontent.com/1735266/39906474-c04174a4-5497-11e8-9657-3f65a59665f9.png)

When I open the RSS feed in a browser tab and download it, it's 3.2 MB. So maybe Feedly can't handle such a big feed.

MathJax accounts for a good proportion of the text; there are long sections that look like this:

> main-B; src: local('MathJax_Main Bold'), local('MathJax_Main-Bold')} @font-face {font-family: MJXc-TeX-main-Bx; src: local('MathJax_Main'); font-weight: bold} @font-face {font-family: MJXc-TeX-main-Bw; src /*1*/: url('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/fonts/HTML-CSS/TeX/eot/MathJax_Main-Bold.eot'); src /*2*/: url('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/fonts/HTML-CSS/TeX/woff/MathJax_Main-Bold.woff') format('woff'), url('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/fonts/HTML-CSS/TeX/otf/MathJax_Main-Bold.otf') format('opentype')} @font-face {font-family: MJXc-TeX-main-I; src: local('MathJax_Main Italic'), local('MathJax_Main-Italic')} @font-face {font-family: MJXc-TeX-main-Ix; src: local('MathJax_Main'); font-style: italic} @font-face {font-family: MJXc-TeX-main-Iw; src /*1*/: url('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/fonts/HTML-CSS/TeX/eot/MathJax_Main-Italic.eot'); src /*2*/: url('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/fonts/HTML-CSS/TeX/woff/MathJax_Main-Italic.woff') format('woff'), url('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/fonts/HTML-CSS/TeX/otf/MathJax_Main-Italic.otf') format('opentype')} @font-face {font-family: MJXc-TeX-main-R; src: local('MathJax_Main'), local('MathJax_Main-Regular')} @font-face {font-family: MJXc-TeX-main-Rw; src /*1*/: url('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/fonts/HTML-CSS/TeX/eot/MathJax_Main-Regular.eot'); src /*2*/: url('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/fonts/HTML-CSS/TeX/woff/MathJ

**Comment by jimrandomh** [comment]
This doesn't currently replicate (the most recent front page posts don't have much LaTeX) but will probably come up repeatedly. There are a couple angles to approach this from:

 * Reduce the bloat from MathJax (will also help with other problems elsewhere)
 * Render MathJax stuff server-side into images for the feed
 * Truncate large posts with a Read More link
 * Adjust how far back feed.xml history goes (maybe dynamically)

This problem will recur and get worse as post volume increases.

**Comment by jimrandomh** [comment]
The MathJax bloat was fixed in https://github.com/LessWrong2/Lesswrong2/pull/716 so this should no longer be an issue.
