### ISSUE TITLE
Some legacy links still not working properly

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#588]
From intercom:

This link: https://www.lesswrong.com/r/discussion/lw/p9e/sam_harris_and_scott_adams_debate_trump_a_model/#comments is broken on this page: https://www.lesswrong.com/posts/ZCir477TEMPN6q5o7/the-dark-arts-examples-from-the-harris-adams-conversation

**Comment by jimrandomh** [comment]
That link seems to work now. There are some types of legacy links that are still broken (eg meetups), but those should already have separate issues open.
