### ISSUE TITLE
Upvote strenght 2 with karma <20

### ISSUE THREAD

**Issue by jbartosik** [LessWrong2/Lesswrong2#614]
Some time ago I noticed my votes change score by 2. According to [strong votes beta announcement](https://www.lesswrong.com/posts/7Sx3CJXA7JHxY2yDG/beta-test-strong-votes) this should happen when I get 1000 karma or more. I have 24 (was ~16 when I noticed my votes having strength of 2).

**Comment by Raemon** [comment]
The strong upvotes thing will take place soon, but hasn't been pushed yet.
Right now second point comes at 5.
ᐧ

**Comment by jbartosik** [comment]
Ah, ok. Thanks for explaining. I didn't think normal votes would change as part of the strong votes.

**Comment by Raemon** [comment]
Yeah, for the past 9 months we've had a different voting strength thing,
where everyone's vote follows the log5 of their karma.
ᐧ
