### ISSUE TITLE
Images missing from Scott Alexander's Diseased Thinking

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#615]
https://www.lesswrong.com/s/NHXY86jBahi968uW4/p/895quRDaK6gR2rM82

And perhaps more generally – is everything from Raikhoth(sp?) gone, and is there a way to systematically get it back?

http://www.raikoth.net/Stuff/disease_first.gif

**Comment by Raemon** [comment]
Presumably we need to chat with Scott about why Raikoth went down and whether we can fix it.

**Comment by jimrandomh** [comment]
There's a copy of at least that particular image on archive.org, so we can repair the post by hand without Scott's intervention. More generally, we should have something that checks posts for broken image- and other links in bulk.

**Comment by jimrandomh** [comment]
There's a much more serious problem with that post: performance loading/rendering the comments is terrible to the point where it crashes the tab sometimes, and definitely isn't reasonable to read.

**Comment by jimrandomh** [comment]
The image is https://web.archive.org/web/20160513102329if_/http://www.raikoth.net/Stuff/disease_first.gif ; can we have this added to the CDN?

**Comment by jimrandomh** [comment]
Note also: this post does not safely roundtrip through the post editor; it converts every `<br>` into a paragraph break, which is a problem because the post represents paragraph breaks as `<br><br>`, so they get doubled. (And also there's a numbered list in the middle which gets double-spaced inappropriately).

**Comment by Discordius** [comment]
CDNd image:
http://res.cloudinary.com/lesswrong-2-0/image/upload/v1531709899/disease_first_tlnfio.gif

**Comment by jimrandomh** [comment]
Fixed. Roundtripping through the editor introduced one formatting glitch which I couldn't easily fix, which is that the post has a numbered list where the line-breaks grew to paragraph-breaks, but that's a trivial thing compared to having a key diagram missing.
