### ISSUE TITLE
Fix 3 Worlds Collide Links

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#625]
Redirects don't always work reliably and these are pointing at the old link-style

https://www.lesswrong.com/posts/HawFh7RvDM4RyoJ2d/three-worlds-collide-0-8

Also maybe make this into a sequence at some point.

**Comment by jimrandomh** [comment]
Whatever legacy-link problem was affecting these, seems to have been fixed at some point. It might still be interesting to gather these into a sequence, but it's not particularly vital (they already have next-chapter and back-to-table-of-contents links).
