### ISSUE TITLE
Sequence Navigation breaks sometimes

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#628]
From intercom:

When I go to this link: https://www.lesswrong.com/s/yFvZa9wkv5JoqhM8F/p/LcEzxX2FNTKbB6KXS the page goes completely blank after a couple of seconds. This also happened yesterday and has not happened on any other page.

From me:

This is the last post in Luke's sequence Rationality and Philosophy, the issue has something to do with the sequence navigation

**Comment by jimrandomh** [comment]
This was the bug where the sequence navigation widget crashed if the next "chapter" in the sequence was empty. It is fixed now.
