### ISSUE TITLE
Constantly consuming CPU even in background

### ISSUE THREAD

**Issue by ChALkeR** [LessWrong2/Lesswrong2#643]
lesswrong.com constantly consumes CPU even when is kept in background (i.e. on an inactive tab).

Single post view (`https://www.lesswrong.com/posts/…/…`).

Chromium 67.0.3396.87, 64-bit, Linux.

htop (note the `TIME+` column which exceeds 1 hour): 
![screenshot_20180620_022649](https://user-images.githubusercontent.com/291301/41629783-178542a2-7434-11e8-84af-0829d5ab5ae1.png)

The CPU consumption is most of the time near 0, but once about every ~20 seconds it peaks to ~50%.

Performance inspector shows that it wakes up on timer every 20 seconds and does something for about 0.6-0.7 seconds:

![screenshot_20180620_025118](https://user-images.githubusercontent.com/291301/41629914-cf78580e-7434-11e8-9a29-e20d52f9199a.png)

Burning CPU and battery in background of everyone who has the site open (including those having that tab inactive for a long time) isn't a good thing to do.

Network inspector shows that it fetches 30 KiB (7 KiB packed) with of JSON every 20 seconds and does something with that. Why exactly is that needed?

**Comment by ChALkeR** [comment]
Network inspector shows that it fetches 30 KiB with of JSON every 20 seconds and does something with that. Why exactly is that needed?

**Comment by Raemon** [comment]
Hmm. We'd turned off our own pings to refresh the page with data several
months ago. Possibly related to Intercom?
ᐧ

**Comment by ChALkeR** [comment]
@Raemon It requests `https://www.lesswrong.com/graphql` every 20 seconds, the activity is probably related to that. According to what I see in JS, it's something apollographql-related on the client side.

**Comment by Discordius** [comment]
From what did you infer that it was requesting /graphql? I have been inspecting the packages, but can only find a ping every 20 seconds to Meteor, as long as the tab is open (which stops 60 seconds after the tab is unfocused).

**Comment by Discordius** [comment]
Actually, nevermind. I found it. Should be pretty straightforward to fix.

**Comment by ChALkeR** [comment]
> From what did you infer that it was requesting /graphql?

@Discordius Both Chrome and Firefox have a built-in inspector tool, which has a «Network» tab, showing the requests the page makes. You also can check the exact time (among other details) by clicking on a request. And you can check where it originated from by hovering the initiator.

That «Network» tab shows that `https://www.lesswrong.com/graphql` is constantly requested every ~20 seconds:

![screenshot_20180620_123330](https://user-images.githubusercontent.com/291301/41650193-242053c4-7486-11e8-8cc9-e7a517d6a902.png)

![screenshot_20180620_123420](https://user-images.githubusercontent.com/291301/41650248-4229e3f8-7486-11e8-9133-b6d888578a7d.png)
![screenshot_20180620_123453](https://user-images.githubusercontent.com/291301/41650284-55789800-7486-11e8-8261-82e49590e7e3.png)


Btw, notice how it sometimes returns 503 error responses (which is out of scope of this report though).

**Comment by ChALkeR** [comment]
Blocking `||www.lesswrong.com/*.js?meteor_js_resource=true` in browser (which is 4.5 MiB JS file) solves this problem at a cost of partially breaking the navigation (and probably something else).

**Comment by Discordius** [comment]
This should now be fixed. `withDocument` was still doing a poll every 20s, which meant we weren't doing any polls on the frontpage, but were still doing a poll on the PostsPage and the UsersProfilePage.

**Comment by ChALkeR** [comment]
Yes, I can confirm that this specific issue looks fixed now, thanks!
