### ISSUE TITLE
Make codeblocks actually work instead of just disappearing

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#672]
To make that happen, we only need to add a block for codeblocks to here in the to-HTML direction: 

https://github.com/LessWrong2/Lesswrong2/blob/devel/packages/lesswrong/lib/editor/utils.js

Probably also a good idea to go the other way around and allow us to import codeblocks, which is just a small block

**Comment by berekuk** [comment]
Can you explain how to reproduce this and give me some more details? Am I correct you're talking about ``` code blocks?

I tried to copy-paste html with <code> in it in draft-js editor, and it worked. I also tried to put ``` block with markdown setting enabled, then disable it again and edit my draft with draft-js editor - that works too.

**Comment by Discordius** [comment]
Ah, yes. The editing part works. But when we translate the content of the editor into HTML, then the codeblock just disappears. So if you save it and then try to view it, the codeblocks should be gone.

The file I linked above includes the two functions we use to translate from draft-js into HTML and the other way around.

**Comment by berekuk** [comment]
Oh, I see! I was looking at the html at /editPost, not at the post itself. Ok.
