### ISSUE TITLE
Stylesheet duplication in MathJax renders

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#702]
LaTeX in posts is rendered with MathJax, which involves putting a fixed `<style>` block into the page. This block gets a duplicate element for each LaTeX element. Not only does this bloat the size of the post HTML, it potentially makes reflow O(n^2) (depending how clever the browser is) since there are `n` elements each with `n` styles applied to them.

**Comment by jimrandomh** [comment]
Each MathJax style block is 17kb. I made a test post made up of short LaTeX elements (x_1..x_20 in a bullet list) and the `<style>` blocks were ~96% of the total post HTML size. Looking at a real post, https://www.lesswrong.com/posts/H7KB44oKoSjSCkpzL/worrying-about-the-vase-whitelisting has 40 copies of the style block (many are in the comments).

**Comment by Discordius** [comment]
Yep, this would be great to fix. Just to check, if you remove all but one style element, does everything still work, or are the style elements slightly different but with lots of overlap? 

I was thinking it was the second, in which it's a really hard problem to fix. If it's the first, then that should be easy to fix.

**Comment by jimrandomh** [comment]
They're identical in the circumstances I tested, but I didn't test yet whether interesting variations in the LaTeX content change the `<style>` contents.

**Comment by Discordius** [comment]
Them changing was my guess, in which case it isn't obvious how much we
could trim it down.

**Comment by jimrandomh** [comment]
I've checked and confirmed that they don't vary among the MathJax elements in posts currently on the front page (which are somewhat varied but not exhaustive), or between inline and block elements. MathJax generates the style from https://github.com/mathjax/MathJax/blob/d6834e56ae6db26fe3215eeeaacf578a501119d6/unpacked/jax/output/CommonHTML/jax.js . There's a big JSON object there which exactly matches the first ~2/3rds of the style tag; the remainder of the style tag consists exclusively of font-related settings, and while it's a little bit dynamic, the dynamism seems to be about which CDN provides the font files, not about the content of the LaTeX itself.
