### ISSUE TITLE
Post editor: Image float doesn't work

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#706]
In the default post editor, insert an image, then click it. You get a row of four icons, showing a left-aligned image, a left-float image, a centered image, and a right-float image. If you pick the left-float or right-float option, it applies the `float:` style, but it applies it to the wrong element so it doesn't actually float, just aligns.

**Comment by Discordius** [comment]
While true, I don't like floating images and expect that they will make
everything horrible. We probably shouldn't make it actually work, and just
have it align like it does right now.

**Comment by jimrandomh** [comment]
In that case, the fix is to change the icons so they don't make it look like they cause floating.

**Comment by Discordius** [comment]
Yep, that seems sensible. Should be easy to do.
