### ISSUE TITLE
Comments on very old posts appear in a nonsensical order.

### ISSUE THREAD

**Issue by andrew-vant** [LessWrong2/Lesswrong2#723]
Comments on very old threads appear in a nonsensical order. Example: Eliezer's "ouch" comment at the top of the comment thread on [original seeing](https://www.lesswrong.com/posts/SA79JMXKWke32A3hG/original-seeing) arrives as a complete non-sequitur. Similar instances appear all over the Sequences.

I think this is because, in the Overcoming Bias days, comments were ordered chronologically and without nesting. There was no structure to indicate who replied to what except the date. That worked fine with flat, chronological threading, but broke with nested, magically-ordered threading. OB was before my time, so I'm not sure, but it fits the observation.

Unless reply references are in the DB somewhere, I don't think there's any automatic way to restructure old comment threads to suit today's nested paradigm. Instead, any post that pre-dates the OB import should be sorted oldest-first, by default. That's how it was done on LW1, and it worked fine, but the feature doesn't seem to have made it to LW2.

(another possibility might be to enlist users in figuring out what the nesting on old threads "should be". I'm not sure what the UI for such a thing might look like, though.)

[edit: if this could be done in such a way that it's inherited by third-party UI's like Greater Wrong, that would be nice, but for all I know that might be impossible]

**Comment by Discordius** [comment]
Yep, this should be straightforward, and allowing greaterwrong to do the same should also be easy.

**Comment by jimrandomh** [comment]
The obvious implementation here is to make the default sort order be chronological iff the post date is older than the OB->LW migration. Other than tell them what the date cutoff we're using is, I don't think there's anything we'd need to do to enable GreaterWrong to do the same.

**Comment by andrew-vant** [comment]
If you can point me to relevant section of the code, I can probably send you a PR.

**Comment by Raemon** [comment]
We've actually got this most of the way finished, just need to push a final
tweak.
