### ISSUE TITLE
Server side N+1 select loading comments

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#750]
When you load a post with N comments, the server does a separate query on each comment to get the current user's vote (or lack of vote). This is very slow if there are a lot of comments.

**Comment by Discordius** [comment]
Best way of fixing this is probably to factor out getting the votes into a non-blocking query, that then enhances the current store. I think that should be pretty straightforward, but I am not super sure. The question is how you would want to query for all the votes, because you need the commentIds for that, and you might not want to send over a query that has a giant array of all the commentIds as parameters, though that might still be fine. We could probably design a fancy graphQL resolver ourselves, that takes in a postId, and returns all your votes for the comments on that post, which the vast majority of time should be much less than the number of comments on a post.

**Comment by jimrandomh** [comment]
Actually, "N+1 select" was a misdiagnosis on my part; something in the stack is already cleverly and combining the queries for us.

Test thread: 1000 comments, of which 500 will be visible, programmatically generated, each with a self-upvote and no other votes. I rendered the post in two different ways: as the logged-in user who made all thousand comments and self-upvoted them, or as a logged out user. Initially, the GraphQL query to load the comments takes 18s for both of these. (Times are based on the `tracing` field in the query response, and include comment loading only.) Playing with the fragment a bit, two components are completely dominating the run time: `allVotes` and `currentUserVotes`. If both are removed, then the query drops from 18s to <1s.

`allVotes` is used only in the commented-out-for-over-reasons hover tooltip, to count the total number of votes. Looking closely, it turns out to just be missing an index and resorting to a column scan. The `votes` table is indexed by and by `_id` and by `_userId+documentId`, but not by `documentId` alone. Adding the missing index cuts the query time for the logged-out view to 6s, and for the logged-in view to 16s.

Most of the remaining 6s comment load is still in `allVotes`. At 12ms/query, this is still surprisingly slow. The obvious strategy here would be to get rid of `allVotes` entirely--put a voteCount field on the comment objects to replace the one thing it's used for, but I want to understand what's going on first. So, following `allVotes` to its implementation, I find the following resolver:

```
const votes = await Connectors.find(Votes, { documentId: document._id });
if (!votes.length) return [];
return Users.restrictViewableFields(currentUser, Votes, votes);
```

This led me to the theory that Connectors.find is returning something surprisingly big (say, with an inlined User object), and `restrictViewableFields` is discarding it. That turns out not to be it--projecting in the query doesn't help. But poking around for *other* places where `restrictViewableFields` might be covering up a massively bulky query, it turns out that comment.userId loads a whole user object -- including the subscriptions. So when you load a thread with a bunch of commenters, internally we're loading a list of the IDs of everything that everyone in that thread has ever posted. It's going through Vulcan's caching and batching layer, so it's surprisingly not bad in the test I'm running, but the giant-user-object subscriptions thing is something we need to address for non-performance reasons also.

So, the next thing to try is: how much overhead is `Connectors.find` adding compared to a raw MongoDB query? As it happens, the collection is right there in the `Votes` object, albeit with a scary underscore, as `Votes._collection`. Replace `Connectors.find` with `await Connectors._collection.find`, and the query goes from 6s to 2s. I'm not sure what value `Connectors` are supposed to be providing, but I didn't even have to change the arguments.

**Comment by Discordius** [comment]
Regarding missing DB indexes: We have warnings for anything that takes more than 50ms, but no other stuff. So my guess is that while the query is non-indexed, we are still getting below 50ms performance, so we didn't notice it.

**Comment by Discordius** [comment]
> it turns out that comment.userId loads a whole user object -- including the subscriptions.

I assume you wanted to say `comment.user`?

**Comment by jimrandomh** [comment]
> I assume you wanted to say `comment.user`?

Strangely, no; in `Vulcan-Starter/packages/example-forum/lib/modules/comments/schema.js`, `userId` has a resolver which loads a whole user object. I am confused by this.

**Comment by Discordius** [comment]
Nope, the resolver defines a new field called `user`. That's what the `fieldName` variable is for: 
```
  userId: {
    type: String,
    optional: true,
    viewableBy: ['guests'],
    insertableBy: ['members'],
    hidden: true,
    resolveAs: {
      fieldName: 'user',
      type: 'User',
      resolver: async (comment, args, {currentUser, Users}) => {
        if (!comment.userId) return null;
        const user = await Users.loader.load(comment.userId);
        return Users.restrictViewableFields(currentUser, Users, user);
      },
      addOriginalField: true
    },
  },
```

**Comment by Discordius** [comment]
If you don't request that field, the resolver doesn't run

**Comment by jimrandomh** [comment]
Ah, that clears up that bit of confusion. It does in fact run on each comment, though. It is at least batched in such a way that if two comments are by the same user, that user is only fetched once.

**Comment by jimrandomh** [comment]
The missing index, query batching for `currentUserVotes` and `allVotes`, and query batching infrastructure: https://github.com/LessWrong2/Lesswrong2/pull/765 .

**Comment by jimrandomh** [comment]
Addressed in https://github.com/LessWrong2/Lesswrong2/pull/765 .
