### ISSUE TITLE
"Move to Alignment Forum" does nothing

### ISSUE THREAD

**Issue by jessica-taylor** [LessWrong2/Lesswrong2#758]
I tried clicking "Move to Alignment Forum" on some comments (both my own and ones by others) on [this post](https://www.lesswrong.com/posts/4xpDnGaKz472qB4LY/buridan-s-ass-in-coordination-games).  It does nothing.  Some errors are displayed in the Javascript console.

![2018-07-25-181247_545x286_scrot](https://user-images.githubusercontent.com/566984/43235685-6df9985e-9036-11e8-8e32-c24991ef43f3.png)

**Comment by Discordius** [comment]
Actually, I think this is related to something deeper. I think you somehow ended up on a choking server instance, which is why you are getting the 503 error. My model suggests that it should work fine if you refresh and try again. Can you let me know whether that works?

**Comment by jessica-taylor** [comment]
Still not working, and still getting GraphQL errors.

**Comment by Discordius** [comment]
Weird, then it's probably something else. @Raemon probably some kind of permission issue, since it works fine for me?

**Comment by Raemon** [comment]
Should be fixed now.
