### ISSUE TITLE
Monitoring to ping us when servers are down/overloaded

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#777]
One of the times we got linked from HN recently, the servers couldn't handle the traffic, and were down until someone noticed, pinged us and we scaled up the server pool. We shouldn't need someone to notice; if clients start getting 503 errors, we should have an automated system paging people.

There are a number of libraries for this; we pretty much just need to pick one and implement it.

**Comment by Discordius** [comment]
We already use Timber, which can send us notifications for error rates
going up, and we could probably also set up Google Analytics to send me
notifications when we get traffic spikes.
