### ISSUE TITLE
Auto-scaling during traffic spikes

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#779]
When we get a spike of traffic - say, because we've been linked from somewhere prominent - someone has to manually adjust the number of servers in the pool. It would be better if we had a service provider that would scale automatically, or if we could hack something onto our existing service provider to make it do that.

**Comment by Discordius** [comment]
I don't think that's possible at all with Meteor Galaxy, 85% certain.

**Comment by jimrandomh** [comment]
Apparently someone built a solution that will auto-scale Meteor Galaxy by... loading the UI in phantomjs and clicking on the buttons. https://github.com/jehartzog/galaxy-autoscale . Unfortunately, he built it on phantomjs, which is unmaintained, and stopped working. I don't think we're desperate enough, but in theory, we could fix it up and use it.

...Or we could just live with manual scaling (probably fine once all the CPU-usage performance bugs are taken care of), or switch to a different provider.
