### ISSUE TITLE
rel=canonical link for syndicated posts should point to source

### ISSUE THREAD

**Issue by trishume** [LessWrong2/Lesswrong2#81]
Currently posts that are syndicated from another blog, such as [this one](https://www.lesserwrong.com/posts/SaYr2PWR5sx6Tc6Bg/epistemic-spot-check-exercise-for-mood-and-anxiety-michael-w) from Aceso Under Glass, have a `<link rel="canonical">` that contains the URL on LessWrong.

IMO `rel=canonical` links like these should point to the blog post on the original site. This is nicer to the author for the purposes of their posts showing up on search engines. I also seem to recall something about Google penalizing sites that appear to be copying content from elsewhere on the internet without `rel=canonical`, but after a cursory search I can't find the article I read, so take that with a grain of salt. But IMO better to be safe.

It would also probably be nice if when viewing the post there was a link at the top or bottom to the original so people can check out the comments there.

┆Issue is synchronized with this [Trello card](https://trello.com/c/TwiKphXt) by [Unito](https://www.unito.io/learn-more)

**Comment by Discordius** [comment]
Ah, yes. I was actually looking into that a while ago. I think both having a link at the top or bottom is a good idea, and removing the `rel=canonical` tag. Will look into how to best do that in the next few days.

**Comment by JanTrooper2** [comment]
This might be solved, but I don't have a way to test it (because I don't have an RSS feed). There is the option "set the canonical url tag on crossposted posts" and admins can also change the canonical url manually.

**Comment by Discordius** [comment]
Yep, this is I think fixed
