### ISSUE TITLE
"Load More" shown on user profile pages when there is no more left to load

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#823]
At the bottom of the Recent Posts and Recent Comments on user profile pages, there's a "Load More" link. This link is present even if there are no more posts/comments left to load; in that case, clicking it does nothing. We should hide the Load More link if there are no more posts/comments left.

**Comment by Raemon** [comment]
Someone else just complained about this, and wanted to ping about it.

**Comment by patbl** [comment]
I don't know whether this is related, but if you keep clicking "Load More" under "Recent Discussion" on the front page, sometimes no new content is loaded. If you keep clicking it after new content fails to be loaded, sometimes a handful of additional items will be loaded, and sometimes no additional items will load.
