### ISSUE TITLE
Glitches caused by styling refactors

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#827]
* ~Fonts on the Daily page are very broken~
 * ~Most text has slightly changed font size (-10%)~
 * ~The LESSWRONG title in the top bar is slightly vertically misaligned~
 * ~Significant portions of the site have changed font to Roboto~
 * ~The post vote icons are misaligned~
 * ~Blockquotes have their left line in the wrong place, and vertically asymmetric padding, changed color, and lost their right margin~
 * Post section hover-overs on the front page are half transparent

**Comment by jimrandomh** [comment]
* Sticky posts lost their pin

**Comment by jimrandomh** [comment]
* Titles of posts/etc in the Sunshine Sidebar hover-over lost their big font (`<h4>`)

**Comment by Discordius** [comment]
Calling this as closed for now. Let me know if I am wrong

**Comment by jimrandomh** [comment]
Blockquotes are fixed. Hovers are fixed for some of the sections, but not all of them; in particular, it's still half-transparent when you hover over the Meta and Daily sections. It's also grayer than it should be (though not quite that extreme) when you hover over section icons (ie, the stars/people left of the comment-count icons).

**Comment by jimrandomh** [comment]
Also `<h4>` is still unstyled inside posts, eg [Biases: An Introduction](https://www.lessestwrong.com/posts/ptxnyfLWqRZ98wnYi/biases-an-introduction).

**Comment by Discordius** [comment]
H4s are now fixed. I will create a new issue for the Meta and Daily sections.
