### ISSUE TITLE
OAuth login broken for Facebook and GitHub logins

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#847]
From Intercom

There may be a problem with the FB login feature, it's is returning an error to the effect of: the redirect URI is not whitelisted in the FB app settings.

![image](https://user-images.githubusercontent.com/3246710/44602583-daa45000-a794-11e8-93cd-2a644fc05f9e.png)

**Comment by Discordius** [comment]
Fixed!
