### ISSUE TITLE
Typography problems

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#851]
The site's typography is pretty bad, especially on non-Mac systems. In particular: text is significantly darker/bolder on Macs, and on Windows/Linux, it's pale to the point of not being very readable. Also, there's too large a size difference between post text and comment text, such that there's no zoom level where both are readable.

**Comment by Discordius** [comment]
Let's break this up into two issues. One is the considered change to Valkyrie, the other one is the comment and post text fonts being too different.
