### ISSUE TITLE
Change font from Warnock to Valkyrie

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#855]
The Warnock font renders badly on Windows; after looking at a few alternatives, we decided Valkyrie looked like an improvement.

**Comment by jimrandomh** [comment]
Site discussion: https://www.lesswrong.com/posts/PfgHiMZ3jF2fifssH/changing-main-content-font-to-valkyrie

**Comment by Discordius** [comment]
This might either turn out to be really easy, or very hard, depending on how much the fonts differ and we would have to rejiggle stuff.
