### ISSUE TITLE
Negative karma comments probably shouldn't appear in PostItem comments

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#868]
a) it's currently producing a weird bug of "the excerpt from the comment appears, but not the full comment, and then it can't be expanded)

b) we probably don't want it there anyway

c) naively hiding them would result in the comments item still turning green, so people's attention would still be snagged

**Comment by Discordius** [comment]
@Raemon This should be closed with a recent PR, if I am not confused.
