### ISSUE TITLE
Parent comments on frontpage don't show good formatting and triple-dot actions are broken

### ISSUE THREAD

**Issue by ben-pace** [LessWrong2/Lesswrong2#887]
The text is mushed together, any quote formatting is gone, and when I clicked the triple-dot menu and hit 'edit', nothing happened. I think this is just for parents of visible comments on frontpage.

**Comment by ben-pace** [comment]
This is also true for comments in people's profiles. I keep seeing comments in Said's profile where he's quoting something, but it doesn't show the quote indent+line.

**Comment by patbl** [comment]
@ben-pace, if I'm understanding the issue correctly, it looks as though it was fixed. Can you confirm?

![image](https://user-images.githubusercontent.com/1735266/62023675-d04dbb80-b186-11e9-9914-bd5bf387ef27.png)

![image](https://user-images.githubusercontent.com/1735266/62023743-228edc80-b187-11e9-8c59-842fb26a72c6.png)
