### ISSUE TITLE
Description meta tag for posts contains escaped HTML

### ISSUE THREAD

**Issue by jglamine** [LessWrong2/Lesswrong2#889]
The "description" meta / head tag contains escaped html. Instead of using the HTML version of the post for the description, we should use the plain-text version.

This will make previews on google and facebook show up correctly.

When implementing this, make sure the server and client rendered head tags are the same.

**Comment by Discordius** [comment]
Should be fixed by: https://github.com/LessWrong2/Lesswrong2/pull/890

Currently testing on QA. Will see whether it works fine.
