### ISSUE TITLE
Deleted comments on LW 1.0 are no longer deleted

### ISSUE THREAD

**Issue by ben-pace** [LessWrong2/Lesswrong2#893]
Looking at this old sequence post: turns out in the import, Caledonian's comment is not deleted. https://www.lesswrong.com/posts/Q4hLMDrFd8fbteeZ8/measuring-optimization-power#3qbXSwnwXwct789j5

I wonder if this has generalised.

**Comment by Discordius** [comment]
Weird, in the database that comment is marked as `spam`. I guess that's how we marked deleted comments from the old OB days. Will quickly make it so that everything marked spam is also deleted.

**Comment by Discordius** [comment]
Fixed by DB operation
