### ISSUE TITLE
Truncated start of preview text

### ISSUE THREAD

**Issue by jpaddison3** [LessWrong2/Lesswrong2#909]
![image](https://user-images.githubusercontent.com/10352319/44915815-f0cd8580-ad2b-11e8-98c3-ba34fede5420.png)
![image](https://user-images.githubusercontent.com/10352319/44915936-47d35a80-ad2c-11e8-9647-7a4c15b9509e.png)

**Comment by Discordius** [comment]
Huh, super interesting. Will take a look.

**Comment by Discordius** [comment]
Lol, turns out `post.body.substring(300)` does not do the same as `post.body.substring(0,300)`. My bad. Will be fixed.

**Comment by Discordius** [comment]
Fixed with PR
