### ISSUE TITLE
Comments won't load on this post

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#948]
From intercom:
 
Comments on old posts (or at least this old post, have not extensively tested) https://www.lesswrong.com/posts/GR9YT9fd6vYfRQZB8/scientifically-optimizing-education-hard-problem-or-solved won't load. This applies if I look for an individual comment or the entire section.

**Comment by Discordius** [comment]
The console says `can't read property deleted of undefined`. This suggest it's a problem with some comment not loading, but us assuming that it loads. Might have to do with the recent "don't load deleted users" change. Should be very easy to fix.
