### ISSUE TITLE
SmartForm's `updateCurrentValues` right now merges arrays by default. This makes it very hard to delete values from arrays. 

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#954]

**Comment by Discordius** [comment]
This Vulcan commit fixes the relevant issue: https://github.com/VulcanJS/Vulcan/commit/2f4a0acb8e461ec5078c346cd0a03592f0baa4d5

But I think there is also a chance some other form components relied on the merging behavior, so we might want to be careful with this, since the default behavior is now replace.

**Comment by jimrandomh** [comment]
Should be fixed now that we're on Vulcan 1.12.
