### ISSUE TITLE
Can't see some links in private messages

### ISSUE THREAD

**Issue by ben-pace** [LessWrong2/Lesswrong2#962]
Not urgent, but if I add hyperlinks to a PM, then after I've sent the message, *I* can no longer see the hyperlink (the text doesn't change colour unless I hover over it). This isn't a problem for the person to whom I send the message I believe, the colour styling is different.

**Comment by jimrandomh** [comment]
This is probably another byproduct of removing Bootstrap.

**Comment by ben-pace** [comment]
I was wrong - you also can't see links that you *receive*. So all link sending in PMs is broken.
